apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - statefulset.yaml

configMapGenerator:
  - name: knowledge-core-redis-entrypoint
    namespace: redis
    files:
      - entrypoint.sh=entrypoint.sh

patches:
  - path: knowledge-core-statefulset-patch.yaml
