apiVersion: v1
kind: Service
metadata:
  name: knowledge-core-knowledge
  labels:
    app.kubernetes.io/name: knowledge-core-knowledge
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: knowledge-core
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: knowledge-core-knowledge
  ports:
    - name: rpc
      port: 8882
      targetPort: rpc
    - name: admin
      port: 8083
      targetPort: admin
