// Code generated by hertz generator.

package gateway

import (
	gatewaymiddleware "github.com/HappyLadySauce/Knowledge-Core/services/gateway/internal/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listpublisheddocumentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	return []app.HandlerFunc{gatewaymiddleware.AuthRateLimit()}
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _documentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpublisheddocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _studioMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listdocumentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _documents0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _document_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applydocumentoperationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setdocumentstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _currentuserMw() []app.HandlerFunc {
	return []app.HandlerFunc{gatewaymiddleware.RequireAuthenticated()}
}

func _healthMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _liveMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _readyMw() []app.HandlerFunc {
	// your code...
	return nil
}
