// Code generated by Kitex v0.16.2. DO NOT EDIT.

package knowledgeservice

import (
	"context"
	common "github.com/HappyLadySauce/Knowledge-Core/kitex_gen/common"
	knowledge "github.com/HappyLadySauce/Knowledge-Core/kitex_gen/knowledge"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Ping(ctx context.Context, request *common.PingRequest, callOptions ...callopt.Option) (r *common.PingResponse, err error)
	Live(ctx context.Context, request *common.PingRequest, callOptions ...callopt.Option) (r *common.PingResponse, err error)
	ListPublishedDocuments(ctx context.Context, request *knowledge.ListDocumentsRequest, callOptions ...callopt.Option) (r *knowledge.DocumentPage, err error)
	GetPublishedDocument(ctx context.Context, request *knowledge.GetPublishedDocumentRequest, callOptions ...callopt.Option) (r *knowledge.DocumentDetail, err error)
	ListDocuments(ctx context.Context, request *knowledge.ListDocumentsRequest, callOptions ...callopt.Option) (r *knowledge.DocumentPage, err error)
	CreateDocument(ctx context.Context, request *knowledge.CreateDocumentRequest, callOptions ...callopt.Option) (r *knowledge.Document, err error)
	GetDocument(ctx context.Context, request *knowledge.DocumentIDRequest, callOptions ...callopt.Option) (r *knowledge.Document, err error)
	UpdateDocument(ctx context.Context, request *knowledge.UpdateDocumentRequest, callOptions ...callopt.Option) (r *knowledge.Document, err error)
	PublishSnapshot(ctx context.Context, request *knowledge.PublishSnapshotRequest, callOptions ...callopt.Option) (r *knowledge.Document, err error)
	ListFolders(ctx context.Context, request *knowledge.ListFoldersRequest, callOptions ...callopt.Option) (r *knowledge.FolderList, err error)
	CreateFolder(ctx context.Context, request *knowledge.CreateFolderRequest, callOptions ...callopt.Option) (r *knowledge.Folder, err error)
	UpdateFolder(ctx context.Context, request *knowledge.UpdateFolderRequest, callOptions ...callopt.Option) (r *knowledge.Folder, err error)
	DeleteFolder(ctx context.Context, request *knowledge.DeleteFolderRequest, callOptions ...callopt.Option) (err error)
	SetPublication(ctx context.Context, request *knowledge.SetPublicationRequest, callOptions ...callopt.Option) (r *knowledge.Document, err error)
	DeleteDocument(ctx context.Context, request *knowledge.DeleteDocumentRequest, callOptions ...callopt.Option) (r *knowledge.Document, err error)
	RestoreDeletedDocument(ctx context.Context, request *knowledge.DocumentIDRequest, callOptions ...callopt.Option) (r *knowledge.Document, err error)
	ListDeletedDocuments(ctx context.Context, request *knowledge.ListDocumentsRequest, callOptions ...callopt.Option) (r *knowledge.DocumentPage, err error)
	ListMembers(ctx context.Context, request *knowledge.DocumentIDRequest, callOptions ...callopt.Option) (r *knowledge.MemberList, err error)
	AddMember(ctx context.Context, request *knowledge.AddMemberRequest, callOptions ...callopt.Option) (r *knowledge.Member, err error)
	UpdateMember(ctx context.Context, request *knowledge.UpdateMemberRequest, callOptions ...callopt.Option) (r *knowledge.Member, err error)
	DeleteMember(ctx context.Context, request *knowledge.DeleteMemberRequest, callOptions ...callopt.Option) (err error)
	ListAttachments(ctx context.Context, request *knowledge.DocumentIDRequest, callOptions ...callopt.Option) (r *knowledge.AttachmentList, err error)
	CreateAttachment(ctx context.Context, request *knowledge.CreateAttachmentRequest, callOptions ...callopt.Option) (r *knowledge.AttachmentUpload, err error)
	CompleteAttachment(ctx context.Context, request *knowledge.AttachmentIDRequest, callOptions ...callopt.Option) (r *knowledge.Attachment, err error)
	DeleteAttachment(ctx context.Context, request *knowledge.AttachmentIDRequest, callOptions ...callopt.Option) (err error)
	GetAttachmentContent(ctx context.Context, request *knowledge.AttachmentContentRequest, callOptions ...callopt.Option) (r *knowledge.AttachmentContent, err error)
	AuthorizeCollaboration(ctx context.Context, request *knowledge.AuthorizeCollaborationRequest, callOptions ...callopt.Option) (r *knowledge.CollaborationAuthorization, err error)
	ProjectCollaboration(ctx context.Context, request *knowledge.ProjectCollaborationRequest, callOptions ...callopt.Option) (err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kKnowledgeServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kKnowledgeServiceClient struct {
	*kClient
}

func (p *kKnowledgeServiceClient) Ping(ctx context.Context, request *common.PingRequest, callOptions ...callopt.Option) (r *common.PingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Ping(ctx, request)
}

func (p *kKnowledgeServiceClient) Live(ctx context.Context, request *common.PingRequest, callOptions ...callopt.Option) (r *common.PingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Live(ctx, request)
}

func (p *kKnowledgeServiceClient) ListPublishedDocuments(ctx context.Context, request *knowledge.ListDocumentsRequest, callOptions ...callopt.Option) (r *knowledge.DocumentPage, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListPublishedDocuments(ctx, request)
}

func (p *kKnowledgeServiceClient) GetPublishedDocument(ctx context.Context, request *knowledge.GetPublishedDocumentRequest, callOptions ...callopt.Option) (r *knowledge.DocumentDetail, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPublishedDocument(ctx, request)
}

func (p *kKnowledgeServiceClient) ListDocuments(ctx context.Context, request *knowledge.ListDocumentsRequest, callOptions ...callopt.Option) (r *knowledge.DocumentPage, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListDocuments(ctx, request)
}

func (p *kKnowledgeServiceClient) CreateDocument(ctx context.Context, request *knowledge.CreateDocumentRequest, callOptions ...callopt.Option) (r *knowledge.Document, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateDocument(ctx, request)
}

func (p *kKnowledgeServiceClient) GetDocument(ctx context.Context, request *knowledge.DocumentIDRequest, callOptions ...callopt.Option) (r *knowledge.Document, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetDocument(ctx, request)
}

func (p *kKnowledgeServiceClient) UpdateDocument(ctx context.Context, request *knowledge.UpdateDocumentRequest, callOptions ...callopt.Option) (r *knowledge.Document, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateDocument(ctx, request)
}

func (p *kKnowledgeServiceClient) PublishSnapshot(ctx context.Context, request *knowledge.PublishSnapshotRequest, callOptions ...callopt.Option) (r *knowledge.Document, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishSnapshot(ctx, request)
}

func (p *kKnowledgeServiceClient) ListFolders(ctx context.Context, request *knowledge.ListFoldersRequest, callOptions ...callopt.Option) (r *knowledge.FolderList, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFolders(ctx, request)
}

func (p *kKnowledgeServiceClient) CreateFolder(ctx context.Context, request *knowledge.CreateFolderRequest, callOptions ...callopt.Option) (r *knowledge.Folder, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateFolder(ctx, request)
}

func (p *kKnowledgeServiceClient) UpdateFolder(ctx context.Context, request *knowledge.UpdateFolderRequest, callOptions ...callopt.Option) (r *knowledge.Folder, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateFolder(ctx, request)
}

func (p *kKnowledgeServiceClient) DeleteFolder(ctx context.Context, request *knowledge.DeleteFolderRequest, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteFolder(ctx, request)
}

func (p *kKnowledgeServiceClient) SetPublication(ctx context.Context, request *knowledge.SetPublicationRequest, callOptions ...callopt.Option) (r *knowledge.Document, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetPublication(ctx, request)
}

func (p *kKnowledgeServiceClient) DeleteDocument(ctx context.Context, request *knowledge.DeleteDocumentRequest, callOptions ...callopt.Option) (r *knowledge.Document, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteDocument(ctx, request)
}

func (p *kKnowledgeServiceClient) RestoreDeletedDocument(ctx context.Context, request *knowledge.DocumentIDRequest, callOptions ...callopt.Option) (r *knowledge.Document, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RestoreDeletedDocument(ctx, request)
}

func (p *kKnowledgeServiceClient) ListDeletedDocuments(ctx context.Context, request *knowledge.ListDocumentsRequest, callOptions ...callopt.Option) (r *knowledge.DocumentPage, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListDeletedDocuments(ctx, request)
}

func (p *kKnowledgeServiceClient) ListMembers(ctx context.Context, request *knowledge.DocumentIDRequest, callOptions ...callopt.Option) (r *knowledge.MemberList, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListMembers(ctx, request)
}

func (p *kKnowledgeServiceClient) AddMember(ctx context.Context, request *knowledge.AddMemberRequest, callOptions ...callopt.Option) (r *knowledge.Member, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddMember(ctx, request)
}

func (p *kKnowledgeServiceClient) UpdateMember(ctx context.Context, request *knowledge.UpdateMemberRequest, callOptions ...callopt.Option) (r *knowledge.Member, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateMember(ctx, request)
}

func (p *kKnowledgeServiceClient) DeleteMember(ctx context.Context, request *knowledge.DeleteMemberRequest, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteMember(ctx, request)
}

func (p *kKnowledgeServiceClient) ListAttachments(ctx context.Context, request *knowledge.DocumentIDRequest, callOptions ...callopt.Option) (r *knowledge.AttachmentList, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAttachments(ctx, request)
}

func (p *kKnowledgeServiceClient) CreateAttachment(ctx context.Context, request *knowledge.CreateAttachmentRequest, callOptions ...callopt.Option) (r *knowledge.AttachmentUpload, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAttachment(ctx, request)
}

func (p *kKnowledgeServiceClient) CompleteAttachment(ctx context.Context, request *knowledge.AttachmentIDRequest, callOptions ...callopt.Option) (r *knowledge.Attachment, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CompleteAttachment(ctx, request)
}

func (p *kKnowledgeServiceClient) DeleteAttachment(ctx context.Context, request *knowledge.AttachmentIDRequest, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteAttachment(ctx, request)
}

func (p *kKnowledgeServiceClient) GetAttachmentContent(ctx context.Context, request *knowledge.AttachmentContentRequest, callOptions ...callopt.Option) (r *knowledge.AttachmentContent, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAttachmentContent(ctx, request)
}

func (p *kKnowledgeServiceClient) AuthorizeCollaboration(ctx context.Context, request *knowledge.AuthorizeCollaborationRequest, callOptions ...callopt.Option) (r *knowledge.CollaborationAuthorization, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AuthorizeCollaboration(ctx, request)
}

func (p *kKnowledgeServiceClient) ProjectCollaboration(ctx context.Context, request *knowledge.ProjectCollaborationRequest, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ProjectCollaboration(ctx, request)
}
