// Code generated by Kitex v0.16.2. DO NOT EDIT.

package knowledgeservice

import (
	"context"
	"errors"
	common "github.com/HappyLadySauce/Knowledge-Core/kitex_gen/common"
	knowledge "github.com/HappyLadySauce/Knowledge-Core/kitex_gen/knowledge"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Ping": kitex.NewMethodInfo(
		pingHandler,
		newKnowledgeServicePingArgs,
		newKnowledgeServicePingResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	knowledgeServiceServiceInfo                = NewServiceInfo()
	knowledgeServiceServiceInfoForClient       = NewServiceInfoForClient()
	knowledgeServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return knowledgeServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return knowledgeServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return knowledgeServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "KnowledgeService"
	handlerType := (*knowledge.KnowledgeService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "knowledge",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func pingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledge.KnowledgeServicePingArgs)
	realResult := result.(*knowledge.KnowledgeServicePingResult)
	success, err := handler.(knowledge.KnowledgeService).Ping(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServicePingArgs() interface{} {
	return knowledge.NewKnowledgeServicePingArgs()
}

func newKnowledgeServicePingResult() interface{} {
	return knowledge.NewKnowledgeServicePingResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Ping(ctx context.Context, request *common.PingRequest) (r *common.PingResponse, err error) {
	var _args knowledge.KnowledgeServicePingArgs
	_args.Request = request
	var _result knowledge.KnowledgeServicePingResult
	if err = p.c.Call(ctx, "Ping", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
