apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: knowledge-core-nacos
  namespace: config-system
spec:
  secretName: knowledge-core-nacos-tls
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - knowledge-core-nacos
    - knowledge-core-nacos.config-system
    - knowledge-core-nacos.config-system.svc
    - knowledge-core-nacos.config-system.svc.cluster.local
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  usages:
    - server auth
  issuerRef:
    name: happyladysauce-ca
    kind: ClusterIssuer
