nacos.server.main.port=8848
server.ssl.enabled=true
server.ssl.certificate=file:/etc/knowledge-core/nacos/tls/tls.crt
server.ssl.certificate-private-key=file:/etc/knowledge-core/nacos/tls/tls.key

nacos.remote.server.rpc.tls.enableTls=true
nacos.remote.server.rpc.tls.compatibility=false
nacos.remote.server.rpc.tls.protocols=TLSv1.2,TLSv1.3
nacos.remote.server.rpc.tls.certChainFile=file:/etc/knowledge-core/nacos/tls/tls.crt
nacos.remote.server.rpc.tls.certPrivateKey=file:/etc/knowledge-core/nacos/tls/tls.key
nacos.remote.server.rpc.tls.trustCollectionCertFile=file:/etc/knowledge-core/nacos/tls/ca.crt
nacos.remote.server.rpc.tls.trustAll=false
nacos.remote.server.rpc.tls.mutualAuthEnable=false

spring.sql.init.platform=postgresql
db.num=1
db.url.0=jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/nacos?connectTimeout=5&socketTimeout=10
db.user.0=${NACOS_DB_USER}
db.password.0=${NACOS_DB_PASSWORD}
db.pool.config.driverClassName=org.postgresql.Driver
db.pool.config.connectionTimeout=10000
db.pool.config.validationTimeout=5000
db.pool.config.maximumPoolSize=10
db.pool.config.minimumIdle=1

management.endpoints.web.exposure.include=health,prometheus
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.max-days=7
server.error.include-message=NEVER

nacos.core.auth.system.type=nacos
nacos.core.auth.enabled=true
nacos.core.auth.admin.enabled=true
nacos.core.auth.console.enabled=true
nacos.core.auth.caching.enabled=false
nacos.core.auth.server.identity.key=${NACOS_AUTH_IDENTITY_KEY}
nacos.core.auth.server.identity.value=${NACOS_AUTH_IDENTITY_VALUE}
nacos.core.auth.plugin.nacos.token.cache.enable=false
nacos.core.auth.plugin.nacos.token.expire.seconds=18000
nacos.core.auth.plugin.nacos.token.secret.key=${NACOS_AUTH_TOKEN}
nacos.core.auth.nacos.anonymous.ai.enabled=false

nacos.console.ui.enabled=false
nacos.naming.empty-service.auto-clean=true
nacos.naming.empty-service.clean.initial-delay-ms=50000
nacos.naming.empty-service.clean.period-time-ms=30000
