apiVersion: v1
kind: Namespace
metadata:
  name: knowledge-core-platform
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: config-system
  labels:
    istio-injection: disabled
