apiVersion: v1
kind: ServiceAccount
metadata:
  name: knowledge-core-platform
  namespace: knowledge-core-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knowledge-core-platform-bootstrap
  namespace: knowledge-core-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knowledge-core-postgres-bootstrap
  namespace: postgresql
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knowledge-core-redis-bootstrap
  namespace: redis
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knowledge-core-nacos
  namespace: config-system
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knowledge-core-nacos-bootstrap
  namespace: config-system
automountServiceAccountToken: false
