apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knowledge-core-nats-data
  namespace: knowledge-core-platform
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knowledge-core-etcd-data
  namespace: knowledge-core-platform
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knowledge-core-minio-data
  namespace: knowledge-core-platform
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knowledge-core-clamav-data
  namespace: knowledge-core-platform
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
