apiVersion: v1
kind: ServiceAccount
metadata:
  name: knowledge-core-gateway
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knowledge-core-identity
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knowledge-core-knowledge
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knowledge-core-collaboration
automountServiceAccountToken: false
