// Code generated by hertz generator.

package gateway

import (
	"context"
	"time"

	gateway "github.com/HappyLadySauce/Knowledge-Core/services/gateway/biz/model/gateway"
	"github.com/HappyLadySauce/Knowledge-Core/services/gateway/internal/middleware"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Live .
// @router /health/live [GET]
func Live(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusOK, healthResponse(0, "ok", "live", middleware.GetRequestID(c)))
}

// Ready .
// @router /health/ready [GET]
func Ready(ctx context.Context, c *app.RequestContext) {
	registry, exists := middleware.HealthRegistry(c)
	if !exists {
		hlog.CtxErrorf(ctx, "health registry is not configured")
		c.JSON(consts.StatusServiceUnavailable, healthResponse(10001, "service unavailable", "not_ready", middleware.GetRequestID(c)))
		return
	}
	checkCtx, cancel := context.WithTimeout(ctx, 2*time.Second)
	defer cancel()
	if err := registry.Ready(checkCtx); err != nil {
		hlog.CtxWarnf(ctx, "readiness check failed: %v", err)
		c.JSON(consts.StatusServiceUnavailable, healthResponse(10001, "service unavailable", "not_ready", middleware.GetRequestID(c)))
		return
	}
	c.JSON(consts.StatusOK, healthResponse(0, "ok", "ready", middleware.GetRequestID(c)))
}

func healthResponse(code int32, message, status, requestID string) *gateway.HealthResponse {
	return &gateway.HealthResponse{
		Code:      code,
		Message:   message,
		Data:      &gateway.HealthData{Status: status, Service: "gateway"},
		RequestID: requestID,
	}
}
