// Code generated by hertz generator. Handler implementations are maintained by the Gateway service.

package gateway

import (
	"context"
	"errors"

	identityv1 "github.com/HappyLadySauce/Knowledge-Core/kitex_gen/identity"
	jsoncodec "github.com/HappyLadySauce/Knowledge-Core/pkg/codec/json"
	gatewaymodel "github.com/HappyLadySauce/Knowledge-Core/services/gateway/biz/model/gateway"
	gatewaymiddleware "github.com/HappyLadySauce/Knowledge-Core/services/gateway/internal/middleware"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

const gatewayServiceName = "gateway"

// Live handles GET /health/live.
func Live(ctx context.Context, request *app.RequestContext) {
	dependencies, ok := gatewaymiddleware.FromRequest(request)
	if !ok {
		gatewaymiddleware.WriteError(ctx, request, gatewaymiddleware.ErrInternal)
		return
	}
	if err := dependencies.Health.Live(ctx); err != nil {
		gatewaymiddleware.WriteError(ctx, request, gatewaymiddleware.ErrNotReady)
		return
	}
	writeHealth(ctx, request, "ok")
}

// Ready handles GET /health/ready.
func Ready(ctx context.Context, request *app.RequestContext) {
	dependencies, ok := gatewaymiddleware.FromRequest(request)
	if !ok {
		gatewaymiddleware.WriteError(ctx, request, gatewaymiddleware.ErrInternal)
		return
	}
	if err := dependencies.Health.Ready(ctx); err != nil {
		gatewaymiddleware.WriteError(ctx, request, gatewaymiddleware.ErrNotReady)
		return
	}
	writeHealth(ctx, request, "ready")
}

// Register handles POST /api/v1/auth/register.
func Register(ctx context.Context, request *app.RequestContext) {
	var input gatewaymodel.RegisterRequest
	if err := decodeBody(request, &input); err != nil {
		gatewaymiddleware.WriteError(ctx, request, gatewaymiddleware.ErrInvalidRequest)
		return
	}
	if input.Username == "" || input.Email == "" || input.Password == "" {
		gatewaymiddleware.WriteError(ctx, request, gatewaymiddleware.ErrInvalidRequest)
		return
	}
	dependencies, ok := gatewaymiddleware.FromRequest(request)
	if !ok {
		gatewaymiddleware.WriteError(ctx, request, gatewaymiddleware.ErrInternal)
		return
	}
	user, err := dependencies.Identity.Register(ctx, &identityv1.RegisterRequest{
		Username: input.Username,
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		gatewaymiddleware.WriteIdentityError(ctx, request, err)
		return
	}
	data, err := toUserData(user)
	if err != nil {
		gatewaymiddleware.WriteError(ctx, request, gatewaymiddleware.ErrInvalidUpstreamResponse)
		return
	}
	requestID, traceID := gatewaymiddleware.ResponseMetadata(ctx, request)
	gatewaymiddleware.WriteJSON(request, consts.StatusCreated, &gatewaymodel.RegisterResponse{
		Code: 0, Message: "ok", Data: data, RequestID: requestID, TraceID: traceID,
	})
}

// Login handles POST /api/v1/auth/login.
func Login(ctx context.Context, request *app.RequestContext) {
	var input gatewaymodel.LoginRequest
	if err := decodeBody(request, &input); err != nil {
		gatewaymiddleware.WriteError(ctx, request, gatewaymiddleware.ErrInvalidRequest)
		return
	}
	if input.Identifier == "" || input.Password == "" {
		gatewaymiddleware.WriteError(ctx, request, gatewaymiddleware.ErrInvalidRequest)
		return
	}
	dependencies, ok := gatewaymiddleware.FromRequest(request)
	if !ok {
		gatewaymiddleware.WriteError(ctx, request, gatewaymiddleware.ErrInternal)
		return
	}
	authentication, err := dependencies.Identity.Authenticate(ctx, &identityv1.AuthenticateRequest{
		Identifier: input.Identifier,
		Password:   input.Password,
	})
	if err != nil {
		gatewaymiddleware.WriteIdentityError(ctx, request, err)
		return
	}
	if authentication == nil || authentication.AccessToken == "" || authentication.ExpiresAtUnix <= 0 {
		gatewaymiddleware.WriteError(ctx, request, gatewaymiddleware.ErrInvalidUpstreamResponse)
		return
	}
	user, err := toUserData(authentication.User)
	if err != nil {
		gatewaymiddleware.WriteError(ctx, request, gatewaymiddleware.ErrInvalidUpstreamResponse)
		return
	}
	requestID, traceID := gatewaymiddleware.ResponseMetadata(ctx, request)
	gatewaymiddleware.WriteJSON(request, consts.StatusOK, &gatewaymodel.LoginResponse{
		Code:    0,
		Message: "ok",
		Data: &gatewaymodel.LoginData{
			User: user, AccessToken: authentication.AccessToken,
			TokenType: "Bearer", ExpiresAtUnix: authentication.ExpiresAtUnix,
		},
		RequestID: requestID,
		TraceID:   traceID,
	})
}

// CurrentUser handles GET /api/v1/users/me.
func CurrentUser(ctx context.Context, request *app.RequestContext) {
	user, ok := gatewaymiddleware.CurrentUser(request)
	if !ok {
		gatewaymiddleware.WriteError(ctx, request, gatewaymiddleware.ErrAuthenticationRequired)
		return
	}
	data, err := toUserData(user)
	if err != nil {
		gatewaymiddleware.WriteError(ctx, request, gatewaymiddleware.ErrInvalidUpstreamResponse)
		return
	}
	requestID, traceID := gatewaymiddleware.ResponseMetadata(ctx, request)
	gatewaymiddleware.WriteJSON(request, consts.StatusOK, &gatewaymodel.CurrentUserResponse{
		Code: 0, Message: "ok", Data: data, RequestID: requestID, TraceID: traceID,
	})
}

func ListPublishedDocuments(ctx context.Context, request *app.RequestContext) {
	writeUnimplemented(ctx, request)
}

func GetPublishedDocument(ctx context.Context, request *app.RequestContext) {
	writeUnimplemented(ctx, request)
}

func ListDocuments(ctx context.Context, request *app.RequestContext) {
	writeUnimplemented(ctx, request)
}

func CreateDocument(ctx context.Context, request *app.RequestContext) {
	writeUnimplemented(ctx, request)
}

func GetDocument(ctx context.Context, request *app.RequestContext) {
	writeUnimplemented(ctx, request)
}

func UpdateDocument(ctx context.Context, request *app.RequestContext) {
	writeUnimplemented(ctx, request)
}

func DeleteDocument(ctx context.Context, request *app.RequestContext) {
	writeUnimplemented(ctx, request)
}

func SetDocumentStatus(ctx context.Context, request *app.RequestContext) {
	writeUnimplemented(ctx, request)
}

func ApplyDocumentOperation(ctx context.Context, request *app.RequestContext) {
	writeUnimplemented(ctx, request)
}

func writeHealth(ctx context.Context, request *app.RequestContext, status string) {
	requestID, traceID := gatewaymiddleware.ResponseMetadata(ctx, request)
	gatewaymiddleware.WriteJSON(request, consts.StatusOK, &gatewaymodel.HealthResponse{
		Code: 0, Message: "ok",
		Data:      &gatewaymodel.HealthData{Status: status, Service: gatewayServiceName},
		RequestID: requestID, TraceID: traceID,
	})
}

func writeUnimplemented(ctx context.Context, request *app.RequestContext) {
	gatewaymiddleware.WriteError(ctx, request, gatewaymiddleware.ErrUnimplemented)
}

func decodeBody(request *app.RequestContext, target any) error {
	if request == nil || target == nil || len(request.Request.Body()) == 0 {
		return errors.New("request body is required")
	}
	return jsoncodec.Unmarshal(request.Request.Body(), target)
}

func toUserData(user *identityv1.User) (*gatewaymodel.UserData, error) {
	if user == nil || user.Id <= 0 || user.Username == "" || user.Email == "" || user.Role == "" || user.Status == "" ||
		user.TokenVersion <= 0 || user.CreatedAtUnix <= 0 || user.UpdatedAtUnix <= 0 {
		return nil, errors.New("identity user is incomplete")
	}
	return &gatewaymodel.UserData{
		ID: user.Id, Username: user.Username, Email: user.Email, Role: user.Role, Status: user.Status,
		Avatar: user.Avatar, Bio: user.Bio, CreatedAtUnix: user.CreatedAtUnix, UpdatedAtUnix: user.UpdatedAtUnix,
	}, nil
}
