// Code generated by Kitex v0.16.2. DO NOT EDIT.

package collaborationservice

import (
	"context"
	"errors"
	collaboration "github.com/HappyLadySauce/Knowledge-Core/kitex_gen/collaboration"
	common "github.com/HappyLadySauce/Knowledge-Core/kitex_gen/common"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Ping": kitex.NewMethodInfo(
		pingHandler,
		newCollaborationServicePingArgs,
		newCollaborationServicePingResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateSession": kitex.NewMethodInfo(
		createSessionHandler,
		newCollaborationServiceCreateSessionArgs,
		newCollaborationServiceCreateSessionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CapturePublicationSnapshot": kitex.NewMethodInfo(
		capturePublicationSnapshotHandler,
		newCollaborationServiceCapturePublicationSnapshotArgs,
		newCollaborationServiceCapturePublicationSnapshotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"PurgeDocument": kitex.NewMethodInfo(
		purgeDocumentHandler,
		newCollaborationServicePurgeDocumentArgs,
		newCollaborationServicePurgeDocumentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	collaborationServiceServiceInfo                = NewServiceInfo()
	collaborationServiceServiceInfoForClient       = NewServiceInfoForClient()
	collaborationServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return collaborationServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return collaborationServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return collaborationServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CollaborationService"
	handlerType := (*collaboration.CollaborationService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "collaboration",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func pingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*collaboration.CollaborationServicePingArgs)
	realResult := result.(*collaboration.CollaborationServicePingResult)
	success, err := handler.(collaboration.CollaborationService).Ping(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCollaborationServicePingArgs() interface{} {
	return collaboration.NewCollaborationServicePingArgs()
}

func newCollaborationServicePingResult() interface{} {
	return collaboration.NewCollaborationServicePingResult()
}

func createSessionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*collaboration.CollaborationServiceCreateSessionArgs)
	realResult := result.(*collaboration.CollaborationServiceCreateSessionResult)
	success, err := handler.(collaboration.CollaborationService).CreateSession(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCollaborationServiceCreateSessionArgs() interface{} {
	return collaboration.NewCollaborationServiceCreateSessionArgs()
}

func newCollaborationServiceCreateSessionResult() interface{} {
	return collaboration.NewCollaborationServiceCreateSessionResult()
}

func capturePublicationSnapshotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*collaboration.CollaborationServiceCapturePublicationSnapshotArgs)
	realResult := result.(*collaboration.CollaborationServiceCapturePublicationSnapshotResult)
	success, err := handler.(collaboration.CollaborationService).CapturePublicationSnapshot(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCollaborationServiceCapturePublicationSnapshotArgs() interface{} {
	return collaboration.NewCollaborationServiceCapturePublicationSnapshotArgs()
}

func newCollaborationServiceCapturePublicationSnapshotResult() interface{} {
	return collaboration.NewCollaborationServiceCapturePublicationSnapshotResult()
}

func purgeDocumentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*collaboration.CollaborationServicePurgeDocumentArgs)

	err := handler.(collaboration.CollaborationService).PurgeDocument(ctx, realArg.Request)
	if err != nil {
		return err
	}

	return nil
}
func newCollaborationServicePurgeDocumentArgs() interface{} {
	return collaboration.NewCollaborationServicePurgeDocumentArgs()
}

func newCollaborationServicePurgeDocumentResult() interface{} {
	return collaboration.NewCollaborationServicePurgeDocumentResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Ping(ctx context.Context, request *common.PingRequest) (r *common.PingResponse, err error) {
	var _args collaboration.CollaborationServicePingArgs
	_args.Request = request
	var _result collaboration.CollaborationServicePingResult
	if err = p.c.Call(ctx, "Ping", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateSession(ctx context.Context, request *collaboration.CreateSessionRequest) (r *collaboration.CollaborationSession, err error) {
	var _args collaboration.CollaborationServiceCreateSessionArgs
	_args.Request = request
	var _result collaboration.CollaborationServiceCreateSessionResult
	if err = p.c.Call(ctx, "CreateSession", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CapturePublicationSnapshot(ctx context.Context, request *collaboration.CapturePublicationSnapshotRequest) (r *collaboration.PublicationSnapshot, err error) {
	var _args collaboration.CollaborationServiceCapturePublicationSnapshotArgs
	_args.Request = request
	var _result collaboration.CollaborationServiceCapturePublicationSnapshotResult
	if err = p.c.Call(ctx, "CapturePublicationSnapshot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PurgeDocument(ctx context.Context, request *collaboration.PurgeDocumentRequest) (err error) {
	var _args collaboration.CollaborationServicePurgeDocumentArgs
	_args.Request = request
	var _result collaboration.CollaborationServicePurgeDocumentResult
	if err = p.c.Call(ctx, "PurgeDocument", &_args, &_result); err != nil {
		return
	}
	return nil
}
