apiVersion: v1
kind: ConfigMap
metadata:
  name: knowledge-core-platform-config
  labels:
    app.kubernetes.io/name: knowledge-core-platform
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: knowledge-core
    app.kubernetes.io/managed-by: kustomize
data:
  PLATFORM_APP_ENVIRONMENT: development
  PLATFORM_POSTGRES_HOST: postgresql.postgresql.svc.cluster.local
  PLATFORM_NATS_SERVERS: nats://nats.nats.svc.cluster.local:4222
