apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ci

resources:
  - infrastructure.yaml
  - rbac.yaml
  - proxy.yaml
  - workflow-template.yaml
  - events.yaml
  - network-policies.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: knowledge-core-ci
    includeTemplates: true
