apiVersion: v1
kind: ServiceAccount
metadata:
  name: knowledge-core-workflow
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knowledge-core-events
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: knowledge-core-workflow
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: knowledge-core-workflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: knowledge-core-workflow
subjects:
  - kind: ServiceAccount
    name: knowledge-core-workflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: knowledge-core-events
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: knowledge-core-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: knowledge-core-events
subjects:
  - kind: ServiceAccount
    name: knowledge-core-events
