import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import * as decoding from "lib0/decoding";
import * as encoding from "lib0/encoding";
import * as awarenessProtocol from "y-protocols/awareness";
import * as syncProtocol from "y-protocols/sync";
import { yXmlFragmentToProseMirrorRootNode } from "y-prosemirror";
import * as Y from "yjs";

import {
  createYjsFixture,
  FRAGMENT_NAME,
  richTextSchema,
} from "../fixture.mjs";

const fixtures = new URL("../fixtures/", import.meta.url);

test("official Yjs applies the committed Yrs update-v1 fixture", async () => {
  const fixture = await readFixture("yrs-update-v1.json");
  const document = new Y.Doc();
  Y.applyUpdate(document, Buffer.from(fixture.state_base64, "base64"));

  assert.equal(
    document.getXmlFragment(FRAGMENT_NAME).toString(),
    fixture.expected_xml,
  );
});

test("committed fixture is generated by official Yjs and y-prosemirror", async () => {
  const fixture = await readFixture("yjs-update-v1.json");
  assert.deepEqual(fixture, createYjsFixture());

  const document = new Y.Doc();
  Y.applyUpdate(document, Buffer.from(fixture.state_base64, "base64"));
  const projection = yXmlFragmentToProseMirrorRootNode(
    document.getXmlFragment(FRAGMENT_NAME),
    richTextSchema,
  ).toJSON();

  assert.deepEqual(toJsonValue(projection), fixture.projection);
  assert.deepEqual(
    toJsonValue(richTextSchema.nodeFromJSON(fixture.projection).toJSON()),
    fixture.projection,
  );
});

test("fixture covers every supported node, mark, and type-specific attribute", async () => {
  const fixture = await readFixture("yjs-update-v1.json");
  const coverage = collectCoverage(fixture.projection);

  assert.deepEqual(coverage.nodes, [
    "attachment",
    "blockquote",
    "bulletList",
    "codeBlock",
    "doc",
    "hardBreak",
    "heading",
    "horizontalRule",
    "image",
    "listItem",
    "orderedList",
    "paragraph",
    "table",
    "tableCell",
    "tableHeader",
    "tableRow",
    "taskItem",
    "taskList",
    "text",
  ]);
  assert.deepEqual(coverage.marks, [
    "bold",
    "code",
    "italic",
    "link",
    "strike",
    "underline",
  ]);
  assert.deepEqual(coverage.attributes, {
    attachment: ["attachmentId", "title"],
    codeBlock: ["language"],
    heading: ["level", "textAlign"],
    image: ["alt", "attachmentId", "title"],
    link: ["href", "title"],
    orderedList: ["start"],
    paragraph: ["textAlign"],
    tableCell: ["colspan", "colwidth", "rowspan"],
    tableHeader: ["colspan", "colwidth", "rowspan"],
    taskItem: ["checked"],
  });
});

test("official Yjs exchanges update-v1 changes in both directions", async () => {
  const fixture = await readFixture("yjs-update-v1.json");
  const source = new Y.Doc();
  const target = new Y.Doc();
  Y.applyUpdate(source, Buffer.from(fixture.state_base64, "base64"));

  const sourceUpdate = Y.encodeStateAsUpdate(
    source,
    Y.encodeStateVector(target),
  );
  Y.applyUpdate(target, sourceUpdate);
  assert.equal(
    target.getXmlFragment(FRAGMENT_NAME).toString(),
    source.getXmlFragment(FRAGMENT_NAME).toString(),
  );

  appendParagraph(target, "update from peer");
  const targetUpdate = Y.encodeStateAsUpdate(
    target,
    Y.encodeStateVector(source),
  );
  assert.ok(targetUpdate.byteLength > 2);
  Y.applyUpdate(source, targetUpdate);

  assert.equal(
    source.getXmlFragment(FRAGMENT_NAME).toString(),
    target.getXmlFragment(FRAGMENT_NAME).toString(),
  );
  assert.deepEqual(
    toJsonValue(
      yXmlFragmentToProseMirrorRootNode(
        source.getXmlFragment(FRAGMENT_NAME),
        richTextSchema,
      ).toJSON(),
    ),
    toJsonValue(
      yXmlFragmentToProseMirrorRootNode(
        target.getXmlFragment(FRAGMENT_NAME),
        richTextSchema,
      ).toJSON(),
    ),
  );
});

test("official y-sync v1 exchanges state without custom framing", () => {
  const source = documentWithText("sync from yjs");
  const target = new Y.Doc();
  const stepOne = encoding.createEncoder();
  syncProtocol.writeSyncStep1(stepOne, target);
  const response = encoding.createEncoder();
  assert.equal(
    syncProtocol.readSyncMessage(
      decoding.createDecoder(encoding.toUint8Array(stepOne)),
      response,
      source,
      null,
    ),
    syncProtocol.messageYjsSyncStep1,
  );
  const acknowledgement = encoding.createEncoder();
  assert.equal(
    syncProtocol.readSyncMessage(
      decoding.createDecoder(encoding.toUint8Array(response)),
      acknowledgement,
      target,
      null,
    ),
    syncProtocol.messageYjsSyncStep2,
  );
  assert.equal(
    target.getXmlFragment(FRAGMENT_NAME).toString(),
    source.getXmlFragment(FRAGMENT_NAME).toString(),
  );
});

test("official awareness update round-trips authenticated client state", () => {
  const source = new awarenessProtocol.Awareness(new Y.Doc());
  const target = new awarenessProtocol.Awareness(new Y.Doc());
  source.setLocalState({ user: { id: 71, username: "interop" } });
  const update = awarenessProtocol.encodeAwarenessUpdate(source, [
    source.clientID,
  ]);
  awarenessProtocol.applyAwarenessUpdate(target, update, "fixture");

  assert.deepEqual(target.getStates().get(source.clientID), {
    user: { id: 71, username: "interop" },
  });
  source.destroy();
  target.destroy();
});

async function readFixture(name) {
  return JSON.parse(await readFile(new URL(name, fixtures), "utf8"));
}

function appendParagraph(document, value) {
  const paragraph = new Y.XmlElement("paragraph");
  paragraph.setAttribute("textAlign", "left");
  const text = new Y.XmlText();
  text.insert(0, value);
  paragraph.insert(0, [text]);
  const fragment = document.getXmlFragment(FRAGMENT_NAME);
  fragment.insert(fragment.length, [paragraph]);
}

function documentWithText(value) {
  const document = new Y.Doc();
  appendParagraph(document, value);
  return document;
}

function collectCoverage(projection) {
  const nodes = new Set();
  const marks = new Set();
  const attributes = new Map();

  const recordAttributes = (type, values) => {
    if (!values) {
      return;
    }
    const names = attributes.get(type) ?? new Set();
    for (const name of Object.keys(values)) {
      names.add(name);
    }
    attributes.set(type, names);
  };

  const visit = (node) => {
    nodes.add(node.type);
    recordAttributes(node.type, node.attrs);
    for (const mark of node.marks ?? []) {
      marks.add(mark.type);
      recordAttributes(mark.type, mark.attrs);
    }
    for (const child of node.content ?? []) {
      visit(child);
    }
  };

  visit(projection);
  return {
    nodes: [...nodes].sort(),
    marks: [...marks].sort(),
    attributes: Object.fromEntries(
      [...attributes]
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([type, names]) => [type, [...names].sort()]),
    ),
  };
}

function toJsonValue(value) {
  return JSON.parse(JSON.stringify(value));
}
