// Code generated by Kitex v0.16.2. DO NOT EDIT.

package platformservice

import (
	"context"
	common "github.com/HappyLadySauce/Knowledge-Core/kitex_gen/common"
	platform "github.com/HappyLadySauce/Knowledge-Core/kitex_gen/platform"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Ping(ctx context.Context, request *common.PingRequest, callOptions ...callopt.Option) (r *common.PingResponse, err error)
	Live(ctx context.Context, request *common.PingRequest, callOptions ...callopt.Option) (r *common.PingResponse, err error)
	GetSiteProfile(ctx context.Context, request *common.EmptyResponse, callOptions ...callopt.Option) (r *platform.SiteProfile, err error)
	GetConfiguration(ctx context.Context, request *platform.GetConfigurationRequest, callOptions ...callopt.Option) (r *platform.Configuration, err error)
	PutConfiguration(ctx context.Context, request *platform.PutConfigurationRequest, callOptions ...callopt.Option) (r *platform.Configuration, err error)
	GetConfigurationDelivery(ctx context.Context, request *platform.GetConfigurationDeliveryRequest, callOptions ...callopt.Option) (r *platform.ConfigurationDelivery, err error)
	GetConsumerConfiguration(ctx context.Context, request *platform.GetConsumerConfigurationRequest, callOptions ...callopt.Option) (r *platform.Configuration, err error)
	GetConsumerState(ctx context.Context, request *platform.GetConsumerStateRequest, callOptions ...callopt.Option) (r *platform.ConsumerConfigurationState, err error)
	ReportConfigurationApply(ctx context.Context, request *platform.ReportConfigurationApplyRequest, callOptions ...callopt.Option) (r *common.EmptyResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kPlatformServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPlatformServiceClient struct {
	*kClient
}

func (p *kPlatformServiceClient) Ping(ctx context.Context, request *common.PingRequest, callOptions ...callopt.Option) (r *common.PingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Ping(ctx, request)
}

func (p *kPlatformServiceClient) Live(ctx context.Context, request *common.PingRequest, callOptions ...callopt.Option) (r *common.PingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Live(ctx, request)
}

func (p *kPlatformServiceClient) GetSiteProfile(ctx context.Context, request *common.EmptyResponse, callOptions ...callopt.Option) (r *platform.SiteProfile, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSiteProfile(ctx, request)
}

func (p *kPlatformServiceClient) GetConfiguration(ctx context.Context, request *platform.GetConfigurationRequest, callOptions ...callopt.Option) (r *platform.Configuration, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConfiguration(ctx, request)
}

func (p *kPlatformServiceClient) PutConfiguration(ctx context.Context, request *platform.PutConfigurationRequest, callOptions ...callopt.Option) (r *platform.Configuration, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PutConfiguration(ctx, request)
}

func (p *kPlatformServiceClient) GetConfigurationDelivery(ctx context.Context, request *platform.GetConfigurationDeliveryRequest, callOptions ...callopt.Option) (r *platform.ConfigurationDelivery, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConfigurationDelivery(ctx, request)
}

func (p *kPlatformServiceClient) GetConsumerConfiguration(ctx context.Context, request *platform.GetConsumerConfigurationRequest, callOptions ...callopt.Option) (r *platform.Configuration, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConsumerConfiguration(ctx, request)
}

func (p *kPlatformServiceClient) GetConsumerState(ctx context.Context, request *platform.GetConsumerStateRequest, callOptions ...callopt.Option) (r *platform.ConsumerConfigurationState, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConsumerState(ctx, request)
}

func (p *kPlatformServiceClient) ReportConfigurationApply(ctx context.Context, request *platform.ReportConfigurationApplyRequest, callOptions ...callopt.Option) (r *common.EmptyResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReportConfigurationApply(ctx, request)
}
