apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: knowledge-core-platform
    newName: harbor.happyladysauce.local/knowledge-core/platform
    newTag: dev
