// Code generated by Kitex v0.16.2. DO NOT EDIT.

package identityservice

import (
	"context"
	"errors"
	common "github.com/HappyLadySauce/Knowledge-Core/kitex_gen/common"
	identity "github.com/HappyLadySauce/Knowledge-Core/kitex_gen/identity"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Ping": kitex.NewMethodInfo(
		pingHandler,
		newIdentityServicePingArgs,
		newIdentityServicePingResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newIdentityServiceRegisterArgs,
		newIdentityServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Authenticate": kitex.NewMethodInfo(
		authenticateHandler,
		newIdentityServiceAuthenticateArgs,
		newIdentityServiceAuthenticateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RefreshSession": kitex.NewMethodInfo(
		refreshSessionHandler,
		newIdentityServiceRefreshSessionArgs,
		newIdentityServiceRefreshSessionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RequestEmailVerification": kitex.NewMethodInfo(
		requestEmailVerificationHandler,
		newIdentityServiceRequestEmailVerificationArgs,
		newIdentityServiceRequestEmailVerificationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"VerifyEmail": kitex.NewMethodInfo(
		verifyEmailHandler,
		newIdentityServiceVerifyEmailArgs,
		newIdentityServiceVerifyEmailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RequestPasswordReset": kitex.NewMethodInfo(
		requestPasswordResetHandler,
		newIdentityServiceRequestPasswordResetArgs,
		newIdentityServiceRequestPasswordResetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ResetPassword": kitex.NewMethodInfo(
		resetPasswordHandler,
		newIdentityServiceResetPasswordArgs,
		newIdentityServiceResetPasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListSessions": kitex.NewMethodInfo(
		listSessionsHandler,
		newIdentityServiceListSessionsArgs,
		newIdentityServiceListSessionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RevokeSession": kitex.NewMethodInfo(
		revokeSessionHandler,
		newIdentityServiceRevokeSessionArgs,
		newIdentityServiceRevokeSessionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RevokeAllSessions": kitex.NewMethodInfo(
		revokeAllSessionsHandler,
		newIdentityServiceRevokeAllSessionsArgs,
		newIdentityServiceRevokeAllSessionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeactivateAccount": kitex.NewMethodInfo(
		deactivateAccountHandler,
		newIdentityServiceDeactivateAccountArgs,
		newIdentityServiceDeactivateAccountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCurrentUser": kitex.NewMethodInfo(
		getCurrentUserHandler,
		newIdentityServiceGetCurrentUserArgs,
		newIdentityServiceGetCurrentUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ResolveUser": kitex.NewMethodInfo(
		resolveUserHandler,
		newIdentityServiceResolveUserArgs,
		newIdentityServiceResolveUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	identityServiceServiceInfo                = NewServiceInfo()
	identityServiceServiceInfoForClient       = NewServiceInfoForClient()
	identityServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return identityServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return identityServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return identityServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "IdentityService"
	handlerType := (*identity.IdentityService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "identity",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func pingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity.IdentityServicePingArgs)
	realResult := result.(*identity.IdentityServicePingResult)
	success, err := handler.(identity.IdentityService).Ping(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServicePingArgs() interface{} {
	return identity.NewIdentityServicePingArgs()
}

func newIdentityServicePingResult() interface{} {
	return identity.NewIdentityServicePingResult()
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity.IdentityServiceRegisterArgs)
	realResult := result.(*identity.IdentityServiceRegisterResult)
	success, err := handler.(identity.IdentityService).Register(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceRegisterArgs() interface{} {
	return identity.NewIdentityServiceRegisterArgs()
}

func newIdentityServiceRegisterResult() interface{} {
	return identity.NewIdentityServiceRegisterResult()
}

func authenticateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity.IdentityServiceAuthenticateArgs)
	realResult := result.(*identity.IdentityServiceAuthenticateResult)
	success, err := handler.(identity.IdentityService).Authenticate(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceAuthenticateArgs() interface{} {
	return identity.NewIdentityServiceAuthenticateArgs()
}

func newIdentityServiceAuthenticateResult() interface{} {
	return identity.NewIdentityServiceAuthenticateResult()
}

func refreshSessionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity.IdentityServiceRefreshSessionArgs)
	realResult := result.(*identity.IdentityServiceRefreshSessionResult)
	success, err := handler.(identity.IdentityService).RefreshSession(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceRefreshSessionArgs() interface{} {
	return identity.NewIdentityServiceRefreshSessionArgs()
}

func newIdentityServiceRefreshSessionResult() interface{} {
	return identity.NewIdentityServiceRefreshSessionResult()
}

func requestEmailVerificationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity.IdentityServiceRequestEmailVerificationArgs)
	realResult := result.(*identity.IdentityServiceRequestEmailVerificationResult)
	success, err := handler.(identity.IdentityService).RequestEmailVerification(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceRequestEmailVerificationArgs() interface{} {
	return identity.NewIdentityServiceRequestEmailVerificationArgs()
}

func newIdentityServiceRequestEmailVerificationResult() interface{} {
	return identity.NewIdentityServiceRequestEmailVerificationResult()
}

func verifyEmailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity.IdentityServiceVerifyEmailArgs)
	realResult := result.(*identity.IdentityServiceVerifyEmailResult)
	success, err := handler.(identity.IdentityService).VerifyEmail(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceVerifyEmailArgs() interface{} {
	return identity.NewIdentityServiceVerifyEmailArgs()
}

func newIdentityServiceVerifyEmailResult() interface{} {
	return identity.NewIdentityServiceVerifyEmailResult()
}

func requestPasswordResetHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity.IdentityServiceRequestPasswordResetArgs)
	realResult := result.(*identity.IdentityServiceRequestPasswordResetResult)
	success, err := handler.(identity.IdentityService).RequestPasswordReset(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceRequestPasswordResetArgs() interface{} {
	return identity.NewIdentityServiceRequestPasswordResetArgs()
}

func newIdentityServiceRequestPasswordResetResult() interface{} {
	return identity.NewIdentityServiceRequestPasswordResetResult()
}

func resetPasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity.IdentityServiceResetPasswordArgs)
	realResult := result.(*identity.IdentityServiceResetPasswordResult)
	success, err := handler.(identity.IdentityService).ResetPassword(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceResetPasswordArgs() interface{} {
	return identity.NewIdentityServiceResetPasswordArgs()
}

func newIdentityServiceResetPasswordResult() interface{} {
	return identity.NewIdentityServiceResetPasswordResult()
}

func listSessionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity.IdentityServiceListSessionsArgs)
	realResult := result.(*identity.IdentityServiceListSessionsResult)
	success, err := handler.(identity.IdentityService).ListSessions(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceListSessionsArgs() interface{} {
	return identity.NewIdentityServiceListSessionsArgs()
}

func newIdentityServiceListSessionsResult() interface{} {
	return identity.NewIdentityServiceListSessionsResult()
}

func revokeSessionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity.IdentityServiceRevokeSessionArgs)
	realResult := result.(*identity.IdentityServiceRevokeSessionResult)
	success, err := handler.(identity.IdentityService).RevokeSession(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceRevokeSessionArgs() interface{} {
	return identity.NewIdentityServiceRevokeSessionArgs()
}

func newIdentityServiceRevokeSessionResult() interface{} {
	return identity.NewIdentityServiceRevokeSessionResult()
}

func revokeAllSessionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity.IdentityServiceRevokeAllSessionsArgs)
	realResult := result.(*identity.IdentityServiceRevokeAllSessionsResult)
	success, err := handler.(identity.IdentityService).RevokeAllSessions(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceRevokeAllSessionsArgs() interface{} {
	return identity.NewIdentityServiceRevokeAllSessionsArgs()
}

func newIdentityServiceRevokeAllSessionsResult() interface{} {
	return identity.NewIdentityServiceRevokeAllSessionsResult()
}

func deactivateAccountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity.IdentityServiceDeactivateAccountArgs)
	realResult := result.(*identity.IdentityServiceDeactivateAccountResult)
	success, err := handler.(identity.IdentityService).DeactivateAccount(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceDeactivateAccountArgs() interface{} {
	return identity.NewIdentityServiceDeactivateAccountArgs()
}

func newIdentityServiceDeactivateAccountResult() interface{} {
	return identity.NewIdentityServiceDeactivateAccountResult()
}

func getCurrentUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity.IdentityServiceGetCurrentUserArgs)
	realResult := result.(*identity.IdentityServiceGetCurrentUserResult)
	success, err := handler.(identity.IdentityService).GetCurrentUser(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceGetCurrentUserArgs() interface{} {
	return identity.NewIdentityServiceGetCurrentUserArgs()
}

func newIdentityServiceGetCurrentUserResult() interface{} {
	return identity.NewIdentityServiceGetCurrentUserResult()
}

func resolveUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity.IdentityServiceResolveUserArgs)
	realResult := result.(*identity.IdentityServiceResolveUserResult)
	success, err := handler.(identity.IdentityService).ResolveUser(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceResolveUserArgs() interface{} {
	return identity.NewIdentityServiceResolveUserArgs()
}

func newIdentityServiceResolveUserResult() interface{} {
	return identity.NewIdentityServiceResolveUserResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Ping(ctx context.Context, request *common.PingRequest) (r *common.PingResponse, err error) {
	var _args identity.IdentityServicePingArgs
	_args.Request = request
	var _result identity.IdentityServicePingResult
	if err = p.c.Call(ctx, "Ping", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Register(ctx context.Context, request *identity.RegisterRequest) (r *identity.User, err error) {
	var _args identity.IdentityServiceRegisterArgs
	_args.Request = request
	var _result identity.IdentityServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Authenticate(ctx context.Context, request *identity.AuthenticateRequest) (r *identity.Authentication, err error) {
	var _args identity.IdentityServiceAuthenticateArgs
	_args.Request = request
	var _result identity.IdentityServiceAuthenticateResult
	if err = p.c.Call(ctx, "Authenticate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefreshSession(ctx context.Context, request *identity.RefreshSessionRequest) (r *identity.Authentication, err error) {
	var _args identity.IdentityServiceRefreshSessionArgs
	_args.Request = request
	var _result identity.IdentityServiceRefreshSessionResult
	if err = p.c.Call(ctx, "RefreshSession", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RequestEmailVerification(ctx context.Context, request *identity.EmailRequest) (r *common.EmptyResponse, err error) {
	var _args identity.IdentityServiceRequestEmailVerificationArgs
	_args.Request = request
	var _result identity.IdentityServiceRequestEmailVerificationResult
	if err = p.c.Call(ctx, "RequestEmailVerification", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyEmail(ctx context.Context, request *identity.EmailTokenRequest) (r *common.EmptyResponse, err error) {
	var _args identity.IdentityServiceVerifyEmailArgs
	_args.Request = request
	var _result identity.IdentityServiceVerifyEmailResult
	if err = p.c.Call(ctx, "VerifyEmail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RequestPasswordReset(ctx context.Context, request *identity.PasswordResetRequestRequest) (r *common.EmptyResponse, err error) {
	var _args identity.IdentityServiceRequestPasswordResetArgs
	_args.Request = request
	var _result identity.IdentityServiceRequestPasswordResetResult
	if err = p.c.Call(ctx, "RequestPasswordReset", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ResetPassword(ctx context.Context, request *identity.PasswordResetRequest) (r *common.EmptyResponse, err error) {
	var _args identity.IdentityServiceResetPasswordArgs
	_args.Request = request
	var _result identity.IdentityServiceResetPasswordResult
	if err = p.c.Call(ctx, "ResetPassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListSessions(ctx context.Context, request *identity.CurrentUserRequest) (r *identity.SessionList, err error) {
	var _args identity.IdentityServiceListSessionsArgs
	_args.Request = request
	var _result identity.IdentityServiceListSessionsResult
	if err = p.c.Call(ctx, "ListSessions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RevokeSession(ctx context.Context, request *identity.SessionRequest) (r *common.EmptyResponse, err error) {
	var _args identity.IdentityServiceRevokeSessionArgs
	_args.Request = request
	var _result identity.IdentityServiceRevokeSessionResult
	if err = p.c.Call(ctx, "RevokeSession", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RevokeAllSessions(ctx context.Context, request *identity.CurrentUserRequest) (r *common.EmptyResponse, err error) {
	var _args identity.IdentityServiceRevokeAllSessionsArgs
	_args.Request = request
	var _result identity.IdentityServiceRevokeAllSessionsResult
	if err = p.c.Call(ctx, "RevokeAllSessions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeactivateAccount(ctx context.Context, request *identity.DeactivateAccountRequest) (r *common.EmptyResponse, err error) {
	var _args identity.IdentityServiceDeactivateAccountArgs
	_args.Request = request
	var _result identity.IdentityServiceDeactivateAccountResult
	if err = p.c.Call(ctx, "DeactivateAccount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCurrentUser(ctx context.Context, request *identity.CurrentUserRequest) (r *identity.User, err error) {
	var _args identity.IdentityServiceGetCurrentUserArgs
	_args.Request = request
	var _result identity.IdentityServiceGetCurrentUserResult
	if err = p.c.Call(ctx, "GetCurrentUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ResolveUser(ctx context.Context, request *identity.ResolveUserRequest) (r *identity.PublicUser, err error) {
	var _args identity.IdentityServiceResolveUserArgs
	_args.Request = request
	var _result identity.IdentityServiceResolveUserResult
	if err = p.c.Call(ctx, "ResolveUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
