// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package common

import (
	"fmt"
)

type PingRequest struct {
	Message *string `thrift:"message,1,optional" frugal:"1,optional,string" json:"message,omitempty"`
}

func NewPingRequest() *PingRequest {
	return &PingRequest{}
}

func (p *PingRequest) InitDefault() {
}

var PingRequest_Message_DEFAULT string

func (p *PingRequest) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return PingRequest_Message_DEFAULT
	}
	return *p.Message
}
func (p *PingRequest) SetMessage(val *string) {
	p.Message = val
}

func (p *PingRequest) IsSetMessage() bool {
	return p.Message != nil
}

func (p *PingRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PingRequest(%+v)", *p)
}

var fieldIDToName_PingRequest = map[int16]string{
	1: "message",
}

type PingResponse struct {
	Service  string `thrift:"service,1,required" frugal:"1,required,string" json:"service"`
	Status   string `thrift:"status,2,required" frugal:"2,required,string" json:"status"`
	UnixTime int64  `thrift:"unix_time,3,required" frugal:"3,required,i64" json:"unix_time"`
}

func NewPingResponse() *PingResponse {
	return &PingResponse{}
}

func (p *PingResponse) InitDefault() {
}

func (p *PingResponse) GetService() (v string) {
	return p.Service
}

func (p *PingResponse) GetStatus() (v string) {
	return p.Status
}

func (p *PingResponse) GetUnixTime() (v int64) {
	return p.UnixTime
}
func (p *PingResponse) SetService(val string) {
	p.Service = val
}
func (p *PingResponse) SetStatus(val string) {
	p.Status = val
}
func (p *PingResponse) SetUnixTime(val int64) {
	p.UnixTime = val
}

func (p *PingResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PingResponse(%+v)", *p)
}

var fieldIDToName_PingResponse = map[int16]string{
	1: "service",
	2: "status",
	3: "unix_time",
}

type EmptyResponse struct {
}

func NewEmptyResponse() *EmptyResponse {
	return &EmptyResponse{}
}

func (p *EmptyResponse) InitDefault() {
}

func (p *EmptyResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EmptyResponse(%+v)", *p)
}

var fieldIDToName_EmptyResponse = map[int16]string{}
