// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package attachment

import (
	"context"
	"fmt"
	"github.com/HappyLadySauce/Knowledge-Core/kitex_gen/common"
)

const (
	CodeInvalidInput = 31001

	CodeNotFound = 31002

	CodeConflict = 31003

	CodeForbidden = 31004

	CodeUnauthenticated = 31005

	CodeUnavailable = 31006

	CodePreconditionFailed = 31007

	CodeGone = 31008

	CodeQuotaExceeded = 31009

	CodeInternal = 31999
)

type Attachment struct {
	Id                string  `thrift:"id,1,required" frugal:"1,required,string" json:"id"`
	OwnerId           int64   `thrift:"owner_id,2,required" frugal:"2,required,i64" json:"owner_id"`
	Filename          string  `thrift:"filename,3,required" frugal:"3,required,string" json:"filename"`
	MediaType         string  `thrift:"media_type,4,required" frugal:"4,required,string" json:"media_type"`
	Category          string  `thrift:"category,5,required" frugal:"5,required,string" json:"category"`
	SizeBytes         int64   `thrift:"size_bytes,6,required" frugal:"6,required,i64" json:"size_bytes"`
	Sha256            string  `thrift:"sha256,7,required" frugal:"7,required,string" json:"sha256"`
	Status            string  `thrift:"status,8,required" frugal:"8,required,string" json:"status"`
	PartSize          int32   `thrift:"part_size,9,required" frugal:"9,required,i32" json:"part_size"`
	PartCount         int32   `thrift:"part_count,10,required" frugal:"10,required,i32" json:"part_count"`
	CreatedAt         string  `thrift:"created_at,11,required" frugal:"11,required,string" json:"created_at"`
	DetectedType      *string `thrift:"detected_type,12,optional" frugal:"12,optional,string" json:"detected_type,omitempty"`
	DownloadUrl       *string `thrift:"download_url,13,optional" frugal:"13,optional,string" json:"download_url,omitempty"`
	DownloadExpiresAt *string `thrift:"download_expires_at,14,optional" frugal:"14,optional,string" json:"download_expires_at,omitempty"`
}

func NewAttachment() *Attachment {
	return &Attachment{}
}

func (p *Attachment) InitDefault() {
}

func (p *Attachment) GetId() (v string) {
	return p.Id
}

func (p *Attachment) GetOwnerId() (v int64) {
	return p.OwnerId
}

func (p *Attachment) GetFilename() (v string) {
	return p.Filename
}

func (p *Attachment) GetMediaType() (v string) {
	return p.MediaType
}

func (p *Attachment) GetCategory() (v string) {
	return p.Category
}

func (p *Attachment) GetSizeBytes() (v int64) {
	return p.SizeBytes
}

func (p *Attachment) GetSha256() (v string) {
	return p.Sha256
}

func (p *Attachment) GetStatus() (v string) {
	return p.Status
}

func (p *Attachment) GetPartSize() (v int32) {
	return p.PartSize
}

func (p *Attachment) GetPartCount() (v int32) {
	return p.PartCount
}

func (p *Attachment) GetCreatedAt() (v string) {
	return p.CreatedAt
}

var Attachment_DetectedType_DEFAULT string

func (p *Attachment) GetDetectedType() (v string) {
	if !p.IsSetDetectedType() {
		return Attachment_DetectedType_DEFAULT
	}
	return *p.DetectedType
}

var Attachment_DownloadUrl_DEFAULT string

func (p *Attachment) GetDownloadUrl() (v string) {
	if !p.IsSetDownloadUrl() {
		return Attachment_DownloadUrl_DEFAULT
	}
	return *p.DownloadUrl
}

var Attachment_DownloadExpiresAt_DEFAULT string

func (p *Attachment) GetDownloadExpiresAt() (v string) {
	if !p.IsSetDownloadExpiresAt() {
		return Attachment_DownloadExpiresAt_DEFAULT
	}
	return *p.DownloadExpiresAt
}
func (p *Attachment) SetId(val string) {
	p.Id = val
}
func (p *Attachment) SetOwnerId(val int64) {
	p.OwnerId = val
}
func (p *Attachment) SetFilename(val string) {
	p.Filename = val
}
func (p *Attachment) SetMediaType(val string) {
	p.MediaType = val
}
func (p *Attachment) SetCategory(val string) {
	p.Category = val
}
func (p *Attachment) SetSizeBytes(val int64) {
	p.SizeBytes = val
}
func (p *Attachment) SetSha256(val string) {
	p.Sha256 = val
}
func (p *Attachment) SetStatus(val string) {
	p.Status = val
}
func (p *Attachment) SetPartSize(val int32) {
	p.PartSize = val
}
func (p *Attachment) SetPartCount(val int32) {
	p.PartCount = val
}
func (p *Attachment) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *Attachment) SetDetectedType(val *string) {
	p.DetectedType = val
}
func (p *Attachment) SetDownloadUrl(val *string) {
	p.DownloadUrl = val
}
func (p *Attachment) SetDownloadExpiresAt(val *string) {
	p.DownloadExpiresAt = val
}

func (p *Attachment) IsSetDetectedType() bool {
	return p.DetectedType != nil
}

func (p *Attachment) IsSetDownloadUrl() bool {
	return p.DownloadUrl != nil
}

func (p *Attachment) IsSetDownloadExpiresAt() bool {
	return p.DownloadExpiresAt != nil
}

func (p *Attachment) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Attachment(%+v)", *p)
}

var fieldIDToName_Attachment = map[int16]string{
	1:  "id",
	2:  "owner_id",
	3:  "filename",
	4:  "media_type",
	5:  "category",
	6:  "size_bytes",
	7:  "sha256",
	8:  "status",
	9:  "part_size",
	10: "part_count",
	11: "created_at",
	12: "detected_type",
	13: "download_url",
	14: "download_expires_at",
}

type UploadPart struct {
	PartNumber int32  `thrift:"part_number,1,required" frugal:"1,required,i32" json:"part_number"`
	Url        string `thrift:"url,2,required" frugal:"2,required,string" json:"url"`
	ExpiresAt  string `thrift:"expires_at,3,required" frugal:"3,required,string" json:"expires_at"`
}

func NewUploadPart() *UploadPart {
	return &UploadPart{}
}

func (p *UploadPart) InitDefault() {
}

func (p *UploadPart) GetPartNumber() (v int32) {
	return p.PartNumber
}

func (p *UploadPart) GetUrl() (v string) {
	return p.Url
}

func (p *UploadPart) GetExpiresAt() (v string) {
	return p.ExpiresAt
}
func (p *UploadPart) SetPartNumber(val int32) {
	p.PartNumber = val
}
func (p *UploadPart) SetUrl(val string) {
	p.Url = val
}
func (p *UploadPart) SetExpiresAt(val string) {
	p.ExpiresAt = val
}

func (p *UploadPart) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadPart(%+v)", *p)
}

var fieldIDToName_UploadPart = map[int16]string{
	1: "part_number",
	2: "url",
	3: "expires_at",
}

type AttachmentUpload struct {
	Attachment *Attachment   `thrift:"attachment,1,required" frugal:"1,required,Attachment" json:"attachment"`
	UploadId   string        `thrift:"upload_id,2,required" frugal:"2,required,string" json:"upload_id"`
	Parts      []*UploadPart `thrift:"parts,3,required" frugal:"3,required,list<UploadPart>" json:"parts"`
	ExpiresAt  string        `thrift:"expires_at,4,required" frugal:"4,required,string" json:"expires_at"`
}

func NewAttachmentUpload() *AttachmentUpload {
	return &AttachmentUpload{}
}

func (p *AttachmentUpload) InitDefault() {
}

var AttachmentUpload_Attachment_DEFAULT *Attachment

func (p *AttachmentUpload) GetAttachment() (v *Attachment) {
	if !p.IsSetAttachment() {
		return AttachmentUpload_Attachment_DEFAULT
	}
	return p.Attachment
}

func (p *AttachmentUpload) GetUploadId() (v string) {
	return p.UploadId
}

func (p *AttachmentUpload) GetParts() (v []*UploadPart) {
	return p.Parts
}

func (p *AttachmentUpload) GetExpiresAt() (v string) {
	return p.ExpiresAt
}
func (p *AttachmentUpload) SetAttachment(val *Attachment) {
	p.Attachment = val
}
func (p *AttachmentUpload) SetUploadId(val string) {
	p.UploadId = val
}
func (p *AttachmentUpload) SetParts(val []*UploadPart) {
	p.Parts = val
}
func (p *AttachmentUpload) SetExpiresAt(val string) {
	p.ExpiresAt = val
}

func (p *AttachmentUpload) IsSetAttachment() bool {
	return p.Attachment != nil
}

func (p *AttachmentUpload) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentUpload(%+v)", *p)
}

var fieldIDToName_AttachmentUpload = map[int16]string{
	1: "attachment",
	2: "upload_id",
	3: "parts",
	4: "expires_at",
}

type CreateAttachmentRequest struct {
	Filename       string  `thrift:"filename,1,required" frugal:"1,required,string" json:"filename"`
	MediaType      string  `thrift:"media_type,2,required" frugal:"2,required,string" json:"media_type"`
	SizeBytes      int64   `thrift:"size_bytes,3,required" frugal:"3,required,i64" json:"size_bytes"`
	IdempotencyKey *string `thrift:"idempotency_key,4,optional" frugal:"4,optional,string" json:"idempotency_key,omitempty"`
}

func NewCreateAttachmentRequest() *CreateAttachmentRequest {
	return &CreateAttachmentRequest{}
}

func (p *CreateAttachmentRequest) InitDefault() {
}

func (p *CreateAttachmentRequest) GetFilename() (v string) {
	return p.Filename
}

func (p *CreateAttachmentRequest) GetMediaType() (v string) {
	return p.MediaType
}

func (p *CreateAttachmentRequest) GetSizeBytes() (v int64) {
	return p.SizeBytes
}

var CreateAttachmentRequest_IdempotencyKey_DEFAULT string

func (p *CreateAttachmentRequest) GetIdempotencyKey() (v string) {
	if !p.IsSetIdempotencyKey() {
		return CreateAttachmentRequest_IdempotencyKey_DEFAULT
	}
	return *p.IdempotencyKey
}
func (p *CreateAttachmentRequest) SetFilename(val string) {
	p.Filename = val
}
func (p *CreateAttachmentRequest) SetMediaType(val string) {
	p.MediaType = val
}
func (p *CreateAttachmentRequest) SetSizeBytes(val int64) {
	p.SizeBytes = val
}
func (p *CreateAttachmentRequest) SetIdempotencyKey(val *string) {
	p.IdempotencyKey = val
}

func (p *CreateAttachmentRequest) IsSetIdempotencyKey() bool {
	return p.IdempotencyKey != nil
}

func (p *CreateAttachmentRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateAttachmentRequest(%+v)", *p)
}

var fieldIDToName_CreateAttachmentRequest = map[int16]string{
	1: "filename",
	2: "media_type",
	3: "size_bytes",
	4: "idempotency_key",
}

type CompletePart struct {
	PartNumber int32  `thrift:"part_number,1,required" frugal:"1,required,i32" json:"part_number"`
	Etag       string `thrift:"etag,2,required" frugal:"2,required,string" json:"etag"`
}

func NewCompletePart() *CompletePart {
	return &CompletePart{}
}

func (p *CompletePart) InitDefault() {
}

func (p *CompletePart) GetPartNumber() (v int32) {
	return p.PartNumber
}

func (p *CompletePart) GetEtag() (v string) {
	return p.Etag
}
func (p *CompletePart) SetPartNumber(val int32) {
	p.PartNumber = val
}
func (p *CompletePart) SetEtag(val string) {
	p.Etag = val
}

func (p *CompletePart) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CompletePart(%+v)", *p)
}

var fieldIDToName_CompletePart = map[int16]string{
	1: "part_number",
	2: "etag",
}

type CompleteAttachmentRequest struct {
	AttachmentId string          `thrift:"attachment_id,1,required" frugal:"1,required,string" json:"attachment_id"`
	UploadId     string          `thrift:"upload_id,2,required" frugal:"2,required,string" json:"upload_id"`
	Parts        []*CompletePart `thrift:"parts,3,required" frugal:"3,required,list<CompletePart>" json:"parts"`
}

func NewCompleteAttachmentRequest() *CompleteAttachmentRequest {
	return &CompleteAttachmentRequest{}
}

func (p *CompleteAttachmentRequest) InitDefault() {
}

func (p *CompleteAttachmentRequest) GetAttachmentId() (v string) {
	return p.AttachmentId
}

func (p *CompleteAttachmentRequest) GetUploadId() (v string) {
	return p.UploadId
}

func (p *CompleteAttachmentRequest) GetParts() (v []*CompletePart) {
	return p.Parts
}
func (p *CompleteAttachmentRequest) SetAttachmentId(val string) {
	p.AttachmentId = val
}
func (p *CompleteAttachmentRequest) SetUploadId(val string) {
	p.UploadId = val
}
func (p *CompleteAttachmentRequest) SetParts(val []*CompletePart) {
	p.Parts = val
}

func (p *CompleteAttachmentRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CompleteAttachmentRequest(%+v)", *p)
}

var fieldIDToName_CompleteAttachmentRequest = map[int16]string{
	1: "attachment_id",
	2: "upload_id",
	3: "parts",
}

type AttachmentIDRequest struct {
	AttachmentId string `thrift:"attachment_id,1,required" frugal:"1,required,string" json:"attachment_id"`
}

func NewAttachmentIDRequest() *AttachmentIDRequest {
	return &AttachmentIDRequest{}
}

func (p *AttachmentIDRequest) InitDefault() {
}

func (p *AttachmentIDRequest) GetAttachmentId() (v string) {
	return p.AttachmentId
}
func (p *AttachmentIDRequest) SetAttachmentId(val string) {
	p.AttachmentId = val
}

func (p *AttachmentIDRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentIDRequest(%+v)", *p)
}

var fieldIDToName_AttachmentIDRequest = map[int16]string{
	1: "attachment_id",
}

type AttachmentPageInfo struct {
	NextCursor *string `thrift:"next_cursor,1,optional" frugal:"1,optional,string" json:"next_cursor,omitempty"`
	HasMore    bool    `thrift:"has_more,2,required" frugal:"2,required,bool" json:"has_more"`
}

func NewAttachmentPageInfo() *AttachmentPageInfo {
	return &AttachmentPageInfo{}
}

func (p *AttachmentPageInfo) InitDefault() {
}

var AttachmentPageInfo_NextCursor_DEFAULT string

func (p *AttachmentPageInfo) GetNextCursor() (v string) {
	if !p.IsSetNextCursor() {
		return AttachmentPageInfo_NextCursor_DEFAULT
	}
	return *p.NextCursor
}

func (p *AttachmentPageInfo) GetHasMore() (v bool) {
	return p.HasMore
}
func (p *AttachmentPageInfo) SetNextCursor(val *string) {
	p.NextCursor = val
}
func (p *AttachmentPageInfo) SetHasMore(val bool) {
	p.HasMore = val
}

func (p *AttachmentPageInfo) IsSetNextCursor() bool {
	return p.NextCursor != nil
}

func (p *AttachmentPageInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentPageInfo(%+v)", *p)
}

var fieldIDToName_AttachmentPageInfo = map[int16]string{
	1: "next_cursor",
	2: "has_more",
}

type AttachmentList struct {
	Items []*Attachment       `thrift:"items,1,required" frugal:"1,required,list<Attachment>" json:"items"`
	Page  *AttachmentPageInfo `thrift:"page,2,optional" frugal:"2,optional,AttachmentPageInfo" json:"page,omitempty"`
}

func NewAttachmentList() *AttachmentList {
	return &AttachmentList{}
}

func (p *AttachmentList) InitDefault() {
}

func (p *AttachmentList) GetItems() (v []*Attachment) {
	return p.Items
}

var AttachmentList_Page_DEFAULT *AttachmentPageInfo

func (p *AttachmentList) GetPage() (v *AttachmentPageInfo) {
	if !p.IsSetPage() {
		return AttachmentList_Page_DEFAULT
	}
	return p.Page
}
func (p *AttachmentList) SetItems(val []*Attachment) {
	p.Items = val
}
func (p *AttachmentList) SetPage(val *AttachmentPageInfo) {
	p.Page = val
}

func (p *AttachmentList) IsSetPage() bool {
	return p.Page != nil
}

func (p *AttachmentList) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentList(%+v)", *p)
}

var fieldIDToName_AttachmentList = map[int16]string{
	1: "items",
	2: "page",
}

type ListAttachmentsRequest struct {
	Status   *string `thrift:"status,1,optional" frugal:"1,optional,string" json:"status,omitempty"`
	Category *string `thrift:"category,2,optional" frugal:"2,optional,string" json:"category,omitempty"`
	Cursor   *string `thrift:"cursor,3,optional" frugal:"3,optional,string" json:"cursor,omitempty"`
	Limit    *int32  `thrift:"limit,4,optional" frugal:"4,optional,i32" json:"limit,omitempty"`
}

func NewListAttachmentsRequest() *ListAttachmentsRequest {
	return &ListAttachmentsRequest{}
}

func (p *ListAttachmentsRequest) InitDefault() {
}

var ListAttachmentsRequest_Status_DEFAULT string

func (p *ListAttachmentsRequest) GetStatus() (v string) {
	if !p.IsSetStatus() {
		return ListAttachmentsRequest_Status_DEFAULT
	}
	return *p.Status
}

var ListAttachmentsRequest_Category_DEFAULT string

func (p *ListAttachmentsRequest) GetCategory() (v string) {
	if !p.IsSetCategory() {
		return ListAttachmentsRequest_Category_DEFAULT
	}
	return *p.Category
}

var ListAttachmentsRequest_Cursor_DEFAULT string

func (p *ListAttachmentsRequest) GetCursor() (v string) {
	if !p.IsSetCursor() {
		return ListAttachmentsRequest_Cursor_DEFAULT
	}
	return *p.Cursor
}

var ListAttachmentsRequest_Limit_DEFAULT int32

func (p *ListAttachmentsRequest) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return ListAttachmentsRequest_Limit_DEFAULT
	}
	return *p.Limit
}
func (p *ListAttachmentsRequest) SetStatus(val *string) {
	p.Status = val
}
func (p *ListAttachmentsRequest) SetCategory(val *string) {
	p.Category = val
}
func (p *ListAttachmentsRequest) SetCursor(val *string) {
	p.Cursor = val
}
func (p *ListAttachmentsRequest) SetLimit(val *int32) {
	p.Limit = val
}

func (p *ListAttachmentsRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *ListAttachmentsRequest) IsSetCategory() bool {
	return p.Category != nil
}

func (p *ListAttachmentsRequest) IsSetCursor() bool {
	return p.Cursor != nil
}

func (p *ListAttachmentsRequest) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *ListAttachmentsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListAttachmentsRequest(%+v)", *p)
}

var fieldIDToName_ListAttachmentsRequest = map[int16]string{
	1: "status",
	2: "category",
	3: "cursor",
	4: "limit",
}

type PublicationReferenceCommand struct {
	MessageId     string   `thrift:"message_id,1,required" frugal:"1,required,string" json:"message_id"`
	DocumentId    string   `thrift:"document_id,2,required" frugal:"2,required,string" json:"document_id"`
	OwnerId       int64    `thrift:"owner_id,3,required" frugal:"3,required,i64" json:"owner_id"`
	Generation    int64    `thrift:"generation,4,required" frugal:"4,required,i64" json:"generation"`
	AttachmentIds []string `thrift:"attachment_ids,5,required" frugal:"5,required,list<string>" json:"attachment_ids"`
}

func NewPublicationReferenceCommand() *PublicationReferenceCommand {
	return &PublicationReferenceCommand{}
}

func (p *PublicationReferenceCommand) InitDefault() {
}

func (p *PublicationReferenceCommand) GetMessageId() (v string) {
	return p.MessageId
}

func (p *PublicationReferenceCommand) GetDocumentId() (v string) {
	return p.DocumentId
}

func (p *PublicationReferenceCommand) GetOwnerId() (v int64) {
	return p.OwnerId
}

func (p *PublicationReferenceCommand) GetGeneration() (v int64) {
	return p.Generation
}

func (p *PublicationReferenceCommand) GetAttachmentIds() (v []string) {
	return p.AttachmentIds
}
func (p *PublicationReferenceCommand) SetMessageId(val string) {
	p.MessageId = val
}
func (p *PublicationReferenceCommand) SetDocumentId(val string) {
	p.DocumentId = val
}
func (p *PublicationReferenceCommand) SetOwnerId(val int64) {
	p.OwnerId = val
}
func (p *PublicationReferenceCommand) SetGeneration(val int64) {
	p.Generation = val
}
func (p *PublicationReferenceCommand) SetAttachmentIds(val []string) {
	p.AttachmentIds = val
}

func (p *PublicationReferenceCommand) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublicationReferenceCommand(%+v)", *p)
}

var fieldIDToName_PublicationReferenceCommand = map[int16]string{
	1: "message_id",
	2: "document_id",
	3: "owner_id",
	4: "generation",
	5: "attachment_ids",
}

type PublicationReferenceStateRequest struct {
	DocumentId string `thrift:"document_id,1,required" frugal:"1,required,string" json:"document_id"`
}

func NewPublicationReferenceStateRequest() *PublicationReferenceStateRequest {
	return &PublicationReferenceStateRequest{}
}

func (p *PublicationReferenceStateRequest) InitDefault() {
}

func (p *PublicationReferenceStateRequest) GetDocumentId() (v string) {
	return p.DocumentId
}
func (p *PublicationReferenceStateRequest) SetDocumentId(val string) {
	p.DocumentId = val
}

func (p *PublicationReferenceStateRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublicationReferenceStateRequest(%+v)", *p)
}

var fieldIDToName_PublicationReferenceStateRequest = map[int16]string{
	1: "document_id",
}

type PublicationReferenceState struct {
	DocumentId       string `thrift:"document_id,1,required" frugal:"1,required,string" json:"document_id"`
	ActiveGeneration int64  `thrift:"active_generation,2,required" frugal:"2,required,i64" json:"active_generation"`
	StagedGeneration *int64 `thrift:"staged_generation,3,optional" frugal:"3,optional,i64" json:"staged_generation,omitempty"`
}

func NewPublicationReferenceState() *PublicationReferenceState {
	return &PublicationReferenceState{}
}

func (p *PublicationReferenceState) InitDefault() {
}

func (p *PublicationReferenceState) GetDocumentId() (v string) {
	return p.DocumentId
}

func (p *PublicationReferenceState) GetActiveGeneration() (v int64) {
	return p.ActiveGeneration
}

var PublicationReferenceState_StagedGeneration_DEFAULT int64

func (p *PublicationReferenceState) GetStagedGeneration() (v int64) {
	if !p.IsSetStagedGeneration() {
		return PublicationReferenceState_StagedGeneration_DEFAULT
	}
	return *p.StagedGeneration
}
func (p *PublicationReferenceState) SetDocumentId(val string) {
	p.DocumentId = val
}
func (p *PublicationReferenceState) SetActiveGeneration(val int64) {
	p.ActiveGeneration = val
}
func (p *PublicationReferenceState) SetStagedGeneration(val *int64) {
	p.StagedGeneration = val
}

func (p *PublicationReferenceState) IsSetStagedGeneration() bool {
	return p.StagedGeneration != nil
}

func (p *PublicationReferenceState) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublicationReferenceState(%+v)", *p)
}

var fieldIDToName_PublicationReferenceState = map[int16]string{
	1: "document_id",
	2: "active_generation",
	3: "staged_generation",
}

type AttachmentContent struct {
	Url       string `thrift:"url,1,required" frugal:"1,required,string" json:"url"`
	ExpiresAt string `thrift:"expires_at,2,required" frugal:"2,required,string" json:"expires_at"`
}

func NewAttachmentContent() *AttachmentContent {
	return &AttachmentContent{}
}

func (p *AttachmentContent) InitDefault() {
}

func (p *AttachmentContent) GetUrl() (v string) {
	return p.Url
}

func (p *AttachmentContent) GetExpiresAt() (v string) {
	return p.ExpiresAt
}
func (p *AttachmentContent) SetUrl(val string) {
	p.Url = val
}
func (p *AttachmentContent) SetExpiresAt(val string) {
	p.ExpiresAt = val
}

func (p *AttachmentContent) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentContent(%+v)", *p)
}

var fieldIDToName_AttachmentContent = map[int16]string{
	1: "url",
	2: "expires_at",
}

type AttachmentService interface {
	Ping(ctx context.Context, request *common.PingRequest) (r *common.PingResponse, err error)

	Live(ctx context.Context, request *common.PingRequest) (r *common.PingResponse, err error)

	CreateAttachment(ctx context.Context, request *CreateAttachmentRequest) (r *AttachmentUpload, err error)

	CompleteAttachment(ctx context.Context, request *CompleteAttachmentRequest) (r *Attachment, err error)

	ListAttachments(ctx context.Context, request *ListAttachmentsRequest) (r *AttachmentList, err error)

	GetAttachment(ctx context.Context, request *AttachmentIDRequest) (r *Attachment, err error)

	TrashAttachment(ctx context.Context, request *AttachmentIDRequest) (err error)

	RestoreAttachment(ctx context.Context, request *AttachmentIDRequest) (r *Attachment, err error)

	StagePublicationReferences(ctx context.Context, request *PublicationReferenceCommand) (err error)

	FinalizePublicationReferences(ctx context.Context, request *PublicationReferenceCommand) (err error)

	ClearPublicationReferences(ctx context.Context, request *PublicationReferenceCommand) (err error)

	GetPublicationReferenceState(ctx context.Context, request *PublicationReferenceStateRequest) (r *PublicationReferenceState, err error)

	GetPublishedAttachmentContent(ctx context.Context, request *AttachmentIDRequest) (r *AttachmentContent, err error)
}

type AttachmentServicePingArgs struct {
	Request *common.PingRequest `thrift:"request,1" frugal:"1,default,common.PingRequest" json:"request"`
}

func NewAttachmentServicePingArgs() *AttachmentServicePingArgs {
	return &AttachmentServicePingArgs{}
}

func (p *AttachmentServicePingArgs) InitDefault() {
}

var AttachmentServicePingArgs_Request_DEFAULT *common.PingRequest

func (p *AttachmentServicePingArgs) GetRequest() (v *common.PingRequest) {
	if !p.IsSetRequest() {
		return AttachmentServicePingArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AttachmentServicePingArgs) SetRequest(val *common.PingRequest) {
	p.Request = val
}

func (p *AttachmentServicePingArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AttachmentServicePingArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServicePingArgs(%+v)", *p)
}

var fieldIDToName_AttachmentServicePingArgs = map[int16]string{
	1: "request",
}

type AttachmentServicePingResult struct {
	Success *common.PingResponse `thrift:"success,0,optional" frugal:"0,optional,common.PingResponse" json:"success,omitempty"`
}

func NewAttachmentServicePingResult() *AttachmentServicePingResult {
	return &AttachmentServicePingResult{}
}

func (p *AttachmentServicePingResult) InitDefault() {
}

var AttachmentServicePingResult_Success_DEFAULT *common.PingResponse

func (p *AttachmentServicePingResult) GetSuccess() (v *common.PingResponse) {
	if !p.IsSetSuccess() {
		return AttachmentServicePingResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AttachmentServicePingResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.PingResponse)
}

func (p *AttachmentServicePingResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AttachmentServicePingResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServicePingResult(%+v)", *p)
}

var fieldIDToName_AttachmentServicePingResult = map[int16]string{
	0: "success",
}

type AttachmentServiceLiveArgs struct {
	Request *common.PingRequest `thrift:"request,1" frugal:"1,default,common.PingRequest" json:"request"`
}

func NewAttachmentServiceLiveArgs() *AttachmentServiceLiveArgs {
	return &AttachmentServiceLiveArgs{}
}

func (p *AttachmentServiceLiveArgs) InitDefault() {
}

var AttachmentServiceLiveArgs_Request_DEFAULT *common.PingRequest

func (p *AttachmentServiceLiveArgs) GetRequest() (v *common.PingRequest) {
	if !p.IsSetRequest() {
		return AttachmentServiceLiveArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AttachmentServiceLiveArgs) SetRequest(val *common.PingRequest) {
	p.Request = val
}

func (p *AttachmentServiceLiveArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AttachmentServiceLiveArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceLiveArgs(%+v)", *p)
}

var fieldIDToName_AttachmentServiceLiveArgs = map[int16]string{
	1: "request",
}

type AttachmentServiceLiveResult struct {
	Success *common.PingResponse `thrift:"success,0,optional" frugal:"0,optional,common.PingResponse" json:"success,omitempty"`
}

func NewAttachmentServiceLiveResult() *AttachmentServiceLiveResult {
	return &AttachmentServiceLiveResult{}
}

func (p *AttachmentServiceLiveResult) InitDefault() {
}

var AttachmentServiceLiveResult_Success_DEFAULT *common.PingResponse

func (p *AttachmentServiceLiveResult) GetSuccess() (v *common.PingResponse) {
	if !p.IsSetSuccess() {
		return AttachmentServiceLiveResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AttachmentServiceLiveResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.PingResponse)
}

func (p *AttachmentServiceLiveResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AttachmentServiceLiveResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceLiveResult(%+v)", *p)
}

var fieldIDToName_AttachmentServiceLiveResult = map[int16]string{
	0: "success",
}

type AttachmentServiceCreateAttachmentArgs struct {
	Request *CreateAttachmentRequest `thrift:"request,1" frugal:"1,default,CreateAttachmentRequest" json:"request"`
}

func NewAttachmentServiceCreateAttachmentArgs() *AttachmentServiceCreateAttachmentArgs {
	return &AttachmentServiceCreateAttachmentArgs{}
}

func (p *AttachmentServiceCreateAttachmentArgs) InitDefault() {
}

var AttachmentServiceCreateAttachmentArgs_Request_DEFAULT *CreateAttachmentRequest

func (p *AttachmentServiceCreateAttachmentArgs) GetRequest() (v *CreateAttachmentRequest) {
	if !p.IsSetRequest() {
		return AttachmentServiceCreateAttachmentArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AttachmentServiceCreateAttachmentArgs) SetRequest(val *CreateAttachmentRequest) {
	p.Request = val
}

func (p *AttachmentServiceCreateAttachmentArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AttachmentServiceCreateAttachmentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceCreateAttachmentArgs(%+v)", *p)
}

var fieldIDToName_AttachmentServiceCreateAttachmentArgs = map[int16]string{
	1: "request",
}

type AttachmentServiceCreateAttachmentResult struct {
	Success *AttachmentUpload `thrift:"success,0,optional" frugal:"0,optional,AttachmentUpload" json:"success,omitempty"`
}

func NewAttachmentServiceCreateAttachmentResult() *AttachmentServiceCreateAttachmentResult {
	return &AttachmentServiceCreateAttachmentResult{}
}

func (p *AttachmentServiceCreateAttachmentResult) InitDefault() {
}

var AttachmentServiceCreateAttachmentResult_Success_DEFAULT *AttachmentUpload

func (p *AttachmentServiceCreateAttachmentResult) GetSuccess() (v *AttachmentUpload) {
	if !p.IsSetSuccess() {
		return AttachmentServiceCreateAttachmentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AttachmentServiceCreateAttachmentResult) SetSuccess(x interface{}) {
	p.Success = x.(*AttachmentUpload)
}

func (p *AttachmentServiceCreateAttachmentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AttachmentServiceCreateAttachmentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceCreateAttachmentResult(%+v)", *p)
}

var fieldIDToName_AttachmentServiceCreateAttachmentResult = map[int16]string{
	0: "success",
}

type AttachmentServiceCompleteAttachmentArgs struct {
	Request *CompleteAttachmentRequest `thrift:"request,1" frugal:"1,default,CompleteAttachmentRequest" json:"request"`
}

func NewAttachmentServiceCompleteAttachmentArgs() *AttachmentServiceCompleteAttachmentArgs {
	return &AttachmentServiceCompleteAttachmentArgs{}
}

func (p *AttachmentServiceCompleteAttachmentArgs) InitDefault() {
}

var AttachmentServiceCompleteAttachmentArgs_Request_DEFAULT *CompleteAttachmentRequest

func (p *AttachmentServiceCompleteAttachmentArgs) GetRequest() (v *CompleteAttachmentRequest) {
	if !p.IsSetRequest() {
		return AttachmentServiceCompleteAttachmentArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AttachmentServiceCompleteAttachmentArgs) SetRequest(val *CompleteAttachmentRequest) {
	p.Request = val
}

func (p *AttachmentServiceCompleteAttachmentArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AttachmentServiceCompleteAttachmentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceCompleteAttachmentArgs(%+v)", *p)
}

var fieldIDToName_AttachmentServiceCompleteAttachmentArgs = map[int16]string{
	1: "request",
}

type AttachmentServiceCompleteAttachmentResult struct {
	Success *Attachment `thrift:"success,0,optional" frugal:"0,optional,Attachment" json:"success,omitempty"`
}

func NewAttachmentServiceCompleteAttachmentResult() *AttachmentServiceCompleteAttachmentResult {
	return &AttachmentServiceCompleteAttachmentResult{}
}

func (p *AttachmentServiceCompleteAttachmentResult) InitDefault() {
}

var AttachmentServiceCompleteAttachmentResult_Success_DEFAULT *Attachment

func (p *AttachmentServiceCompleteAttachmentResult) GetSuccess() (v *Attachment) {
	if !p.IsSetSuccess() {
		return AttachmentServiceCompleteAttachmentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AttachmentServiceCompleteAttachmentResult) SetSuccess(x interface{}) {
	p.Success = x.(*Attachment)
}

func (p *AttachmentServiceCompleteAttachmentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AttachmentServiceCompleteAttachmentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceCompleteAttachmentResult(%+v)", *p)
}

var fieldIDToName_AttachmentServiceCompleteAttachmentResult = map[int16]string{
	0: "success",
}

type AttachmentServiceListAttachmentsArgs struct {
	Request *ListAttachmentsRequest `thrift:"request,1" frugal:"1,default,ListAttachmentsRequest" json:"request"`
}

func NewAttachmentServiceListAttachmentsArgs() *AttachmentServiceListAttachmentsArgs {
	return &AttachmentServiceListAttachmentsArgs{}
}

func (p *AttachmentServiceListAttachmentsArgs) InitDefault() {
}

var AttachmentServiceListAttachmentsArgs_Request_DEFAULT *ListAttachmentsRequest

func (p *AttachmentServiceListAttachmentsArgs) GetRequest() (v *ListAttachmentsRequest) {
	if !p.IsSetRequest() {
		return AttachmentServiceListAttachmentsArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AttachmentServiceListAttachmentsArgs) SetRequest(val *ListAttachmentsRequest) {
	p.Request = val
}

func (p *AttachmentServiceListAttachmentsArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AttachmentServiceListAttachmentsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceListAttachmentsArgs(%+v)", *p)
}

var fieldIDToName_AttachmentServiceListAttachmentsArgs = map[int16]string{
	1: "request",
}

type AttachmentServiceListAttachmentsResult struct {
	Success *AttachmentList `thrift:"success,0,optional" frugal:"0,optional,AttachmentList" json:"success,omitempty"`
}

func NewAttachmentServiceListAttachmentsResult() *AttachmentServiceListAttachmentsResult {
	return &AttachmentServiceListAttachmentsResult{}
}

func (p *AttachmentServiceListAttachmentsResult) InitDefault() {
}

var AttachmentServiceListAttachmentsResult_Success_DEFAULT *AttachmentList

func (p *AttachmentServiceListAttachmentsResult) GetSuccess() (v *AttachmentList) {
	if !p.IsSetSuccess() {
		return AttachmentServiceListAttachmentsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AttachmentServiceListAttachmentsResult) SetSuccess(x interface{}) {
	p.Success = x.(*AttachmentList)
}

func (p *AttachmentServiceListAttachmentsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AttachmentServiceListAttachmentsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceListAttachmentsResult(%+v)", *p)
}

var fieldIDToName_AttachmentServiceListAttachmentsResult = map[int16]string{
	0: "success",
}

type AttachmentServiceGetAttachmentArgs struct {
	Request *AttachmentIDRequest `thrift:"request,1" frugal:"1,default,AttachmentIDRequest" json:"request"`
}

func NewAttachmentServiceGetAttachmentArgs() *AttachmentServiceGetAttachmentArgs {
	return &AttachmentServiceGetAttachmentArgs{}
}

func (p *AttachmentServiceGetAttachmentArgs) InitDefault() {
}

var AttachmentServiceGetAttachmentArgs_Request_DEFAULT *AttachmentIDRequest

func (p *AttachmentServiceGetAttachmentArgs) GetRequest() (v *AttachmentIDRequest) {
	if !p.IsSetRequest() {
		return AttachmentServiceGetAttachmentArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AttachmentServiceGetAttachmentArgs) SetRequest(val *AttachmentIDRequest) {
	p.Request = val
}

func (p *AttachmentServiceGetAttachmentArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AttachmentServiceGetAttachmentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceGetAttachmentArgs(%+v)", *p)
}

var fieldIDToName_AttachmentServiceGetAttachmentArgs = map[int16]string{
	1: "request",
}

type AttachmentServiceGetAttachmentResult struct {
	Success *Attachment `thrift:"success,0,optional" frugal:"0,optional,Attachment" json:"success,omitempty"`
}

func NewAttachmentServiceGetAttachmentResult() *AttachmentServiceGetAttachmentResult {
	return &AttachmentServiceGetAttachmentResult{}
}

func (p *AttachmentServiceGetAttachmentResult) InitDefault() {
}

var AttachmentServiceGetAttachmentResult_Success_DEFAULT *Attachment

func (p *AttachmentServiceGetAttachmentResult) GetSuccess() (v *Attachment) {
	if !p.IsSetSuccess() {
		return AttachmentServiceGetAttachmentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AttachmentServiceGetAttachmentResult) SetSuccess(x interface{}) {
	p.Success = x.(*Attachment)
}

func (p *AttachmentServiceGetAttachmentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AttachmentServiceGetAttachmentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceGetAttachmentResult(%+v)", *p)
}

var fieldIDToName_AttachmentServiceGetAttachmentResult = map[int16]string{
	0: "success",
}

type AttachmentServiceTrashAttachmentArgs struct {
	Request *AttachmentIDRequest `thrift:"request,1" frugal:"1,default,AttachmentIDRequest" json:"request"`
}

func NewAttachmentServiceTrashAttachmentArgs() *AttachmentServiceTrashAttachmentArgs {
	return &AttachmentServiceTrashAttachmentArgs{}
}

func (p *AttachmentServiceTrashAttachmentArgs) InitDefault() {
}

var AttachmentServiceTrashAttachmentArgs_Request_DEFAULT *AttachmentIDRequest

func (p *AttachmentServiceTrashAttachmentArgs) GetRequest() (v *AttachmentIDRequest) {
	if !p.IsSetRequest() {
		return AttachmentServiceTrashAttachmentArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AttachmentServiceTrashAttachmentArgs) SetRequest(val *AttachmentIDRequest) {
	p.Request = val
}

func (p *AttachmentServiceTrashAttachmentArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AttachmentServiceTrashAttachmentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceTrashAttachmentArgs(%+v)", *p)
}

var fieldIDToName_AttachmentServiceTrashAttachmentArgs = map[int16]string{
	1: "request",
}

type AttachmentServiceTrashAttachmentResult struct {
}

func NewAttachmentServiceTrashAttachmentResult() *AttachmentServiceTrashAttachmentResult {
	return &AttachmentServiceTrashAttachmentResult{}
}

func (p *AttachmentServiceTrashAttachmentResult) InitDefault() {
}

func (p *AttachmentServiceTrashAttachmentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceTrashAttachmentResult(%+v)", *p)
}

var fieldIDToName_AttachmentServiceTrashAttachmentResult = map[int16]string{}

type AttachmentServiceRestoreAttachmentArgs struct {
	Request *AttachmentIDRequest `thrift:"request,1" frugal:"1,default,AttachmentIDRequest" json:"request"`
}

func NewAttachmentServiceRestoreAttachmentArgs() *AttachmentServiceRestoreAttachmentArgs {
	return &AttachmentServiceRestoreAttachmentArgs{}
}

func (p *AttachmentServiceRestoreAttachmentArgs) InitDefault() {
}

var AttachmentServiceRestoreAttachmentArgs_Request_DEFAULT *AttachmentIDRequest

func (p *AttachmentServiceRestoreAttachmentArgs) GetRequest() (v *AttachmentIDRequest) {
	if !p.IsSetRequest() {
		return AttachmentServiceRestoreAttachmentArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AttachmentServiceRestoreAttachmentArgs) SetRequest(val *AttachmentIDRequest) {
	p.Request = val
}

func (p *AttachmentServiceRestoreAttachmentArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AttachmentServiceRestoreAttachmentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceRestoreAttachmentArgs(%+v)", *p)
}

var fieldIDToName_AttachmentServiceRestoreAttachmentArgs = map[int16]string{
	1: "request",
}

type AttachmentServiceRestoreAttachmentResult struct {
	Success *Attachment `thrift:"success,0,optional" frugal:"0,optional,Attachment" json:"success,omitempty"`
}

func NewAttachmentServiceRestoreAttachmentResult() *AttachmentServiceRestoreAttachmentResult {
	return &AttachmentServiceRestoreAttachmentResult{}
}

func (p *AttachmentServiceRestoreAttachmentResult) InitDefault() {
}

var AttachmentServiceRestoreAttachmentResult_Success_DEFAULT *Attachment

func (p *AttachmentServiceRestoreAttachmentResult) GetSuccess() (v *Attachment) {
	if !p.IsSetSuccess() {
		return AttachmentServiceRestoreAttachmentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AttachmentServiceRestoreAttachmentResult) SetSuccess(x interface{}) {
	p.Success = x.(*Attachment)
}

func (p *AttachmentServiceRestoreAttachmentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AttachmentServiceRestoreAttachmentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceRestoreAttachmentResult(%+v)", *p)
}

var fieldIDToName_AttachmentServiceRestoreAttachmentResult = map[int16]string{
	0: "success",
}

type AttachmentServiceStagePublicationReferencesArgs struct {
	Request *PublicationReferenceCommand `thrift:"request,1" frugal:"1,default,PublicationReferenceCommand" json:"request"`
}

func NewAttachmentServiceStagePublicationReferencesArgs() *AttachmentServiceStagePublicationReferencesArgs {
	return &AttachmentServiceStagePublicationReferencesArgs{}
}

func (p *AttachmentServiceStagePublicationReferencesArgs) InitDefault() {
}

var AttachmentServiceStagePublicationReferencesArgs_Request_DEFAULT *PublicationReferenceCommand

func (p *AttachmentServiceStagePublicationReferencesArgs) GetRequest() (v *PublicationReferenceCommand) {
	if !p.IsSetRequest() {
		return AttachmentServiceStagePublicationReferencesArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AttachmentServiceStagePublicationReferencesArgs) SetRequest(val *PublicationReferenceCommand) {
	p.Request = val
}

func (p *AttachmentServiceStagePublicationReferencesArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AttachmentServiceStagePublicationReferencesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceStagePublicationReferencesArgs(%+v)", *p)
}

var fieldIDToName_AttachmentServiceStagePublicationReferencesArgs = map[int16]string{
	1: "request",
}

type AttachmentServiceStagePublicationReferencesResult struct {
}

func NewAttachmentServiceStagePublicationReferencesResult() *AttachmentServiceStagePublicationReferencesResult {
	return &AttachmentServiceStagePublicationReferencesResult{}
}

func (p *AttachmentServiceStagePublicationReferencesResult) InitDefault() {
}

func (p *AttachmentServiceStagePublicationReferencesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceStagePublicationReferencesResult(%+v)", *p)
}

var fieldIDToName_AttachmentServiceStagePublicationReferencesResult = map[int16]string{}

type AttachmentServiceFinalizePublicationReferencesArgs struct {
	Request *PublicationReferenceCommand `thrift:"request,1" frugal:"1,default,PublicationReferenceCommand" json:"request"`
}

func NewAttachmentServiceFinalizePublicationReferencesArgs() *AttachmentServiceFinalizePublicationReferencesArgs {
	return &AttachmentServiceFinalizePublicationReferencesArgs{}
}

func (p *AttachmentServiceFinalizePublicationReferencesArgs) InitDefault() {
}

var AttachmentServiceFinalizePublicationReferencesArgs_Request_DEFAULT *PublicationReferenceCommand

func (p *AttachmentServiceFinalizePublicationReferencesArgs) GetRequest() (v *PublicationReferenceCommand) {
	if !p.IsSetRequest() {
		return AttachmentServiceFinalizePublicationReferencesArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AttachmentServiceFinalizePublicationReferencesArgs) SetRequest(val *PublicationReferenceCommand) {
	p.Request = val
}

func (p *AttachmentServiceFinalizePublicationReferencesArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AttachmentServiceFinalizePublicationReferencesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceFinalizePublicationReferencesArgs(%+v)", *p)
}

var fieldIDToName_AttachmentServiceFinalizePublicationReferencesArgs = map[int16]string{
	1: "request",
}

type AttachmentServiceFinalizePublicationReferencesResult struct {
}

func NewAttachmentServiceFinalizePublicationReferencesResult() *AttachmentServiceFinalizePublicationReferencesResult {
	return &AttachmentServiceFinalizePublicationReferencesResult{}
}

func (p *AttachmentServiceFinalizePublicationReferencesResult) InitDefault() {
}

func (p *AttachmentServiceFinalizePublicationReferencesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceFinalizePublicationReferencesResult(%+v)", *p)
}

var fieldIDToName_AttachmentServiceFinalizePublicationReferencesResult = map[int16]string{}

type AttachmentServiceClearPublicationReferencesArgs struct {
	Request *PublicationReferenceCommand `thrift:"request,1" frugal:"1,default,PublicationReferenceCommand" json:"request"`
}

func NewAttachmentServiceClearPublicationReferencesArgs() *AttachmentServiceClearPublicationReferencesArgs {
	return &AttachmentServiceClearPublicationReferencesArgs{}
}

func (p *AttachmentServiceClearPublicationReferencesArgs) InitDefault() {
}

var AttachmentServiceClearPublicationReferencesArgs_Request_DEFAULT *PublicationReferenceCommand

func (p *AttachmentServiceClearPublicationReferencesArgs) GetRequest() (v *PublicationReferenceCommand) {
	if !p.IsSetRequest() {
		return AttachmentServiceClearPublicationReferencesArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AttachmentServiceClearPublicationReferencesArgs) SetRequest(val *PublicationReferenceCommand) {
	p.Request = val
}

func (p *AttachmentServiceClearPublicationReferencesArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AttachmentServiceClearPublicationReferencesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceClearPublicationReferencesArgs(%+v)", *p)
}

var fieldIDToName_AttachmentServiceClearPublicationReferencesArgs = map[int16]string{
	1: "request",
}

type AttachmentServiceClearPublicationReferencesResult struct {
}

func NewAttachmentServiceClearPublicationReferencesResult() *AttachmentServiceClearPublicationReferencesResult {
	return &AttachmentServiceClearPublicationReferencesResult{}
}

func (p *AttachmentServiceClearPublicationReferencesResult) InitDefault() {
}

func (p *AttachmentServiceClearPublicationReferencesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceClearPublicationReferencesResult(%+v)", *p)
}

var fieldIDToName_AttachmentServiceClearPublicationReferencesResult = map[int16]string{}

type AttachmentServiceGetPublicationReferenceStateArgs struct {
	Request *PublicationReferenceStateRequest `thrift:"request,1" frugal:"1,default,PublicationReferenceStateRequest" json:"request"`
}

func NewAttachmentServiceGetPublicationReferenceStateArgs() *AttachmentServiceGetPublicationReferenceStateArgs {
	return &AttachmentServiceGetPublicationReferenceStateArgs{}
}

func (p *AttachmentServiceGetPublicationReferenceStateArgs) InitDefault() {
}

var AttachmentServiceGetPublicationReferenceStateArgs_Request_DEFAULT *PublicationReferenceStateRequest

func (p *AttachmentServiceGetPublicationReferenceStateArgs) GetRequest() (v *PublicationReferenceStateRequest) {
	if !p.IsSetRequest() {
		return AttachmentServiceGetPublicationReferenceStateArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AttachmentServiceGetPublicationReferenceStateArgs) SetRequest(val *PublicationReferenceStateRequest) {
	p.Request = val
}

func (p *AttachmentServiceGetPublicationReferenceStateArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AttachmentServiceGetPublicationReferenceStateArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceGetPublicationReferenceStateArgs(%+v)", *p)
}

var fieldIDToName_AttachmentServiceGetPublicationReferenceStateArgs = map[int16]string{
	1: "request",
}

type AttachmentServiceGetPublicationReferenceStateResult struct {
	Success *PublicationReferenceState `thrift:"success,0,optional" frugal:"0,optional,PublicationReferenceState" json:"success,omitempty"`
}

func NewAttachmentServiceGetPublicationReferenceStateResult() *AttachmentServiceGetPublicationReferenceStateResult {
	return &AttachmentServiceGetPublicationReferenceStateResult{}
}

func (p *AttachmentServiceGetPublicationReferenceStateResult) InitDefault() {
}

var AttachmentServiceGetPublicationReferenceStateResult_Success_DEFAULT *PublicationReferenceState

func (p *AttachmentServiceGetPublicationReferenceStateResult) GetSuccess() (v *PublicationReferenceState) {
	if !p.IsSetSuccess() {
		return AttachmentServiceGetPublicationReferenceStateResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AttachmentServiceGetPublicationReferenceStateResult) SetSuccess(x interface{}) {
	p.Success = x.(*PublicationReferenceState)
}

func (p *AttachmentServiceGetPublicationReferenceStateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AttachmentServiceGetPublicationReferenceStateResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceGetPublicationReferenceStateResult(%+v)", *p)
}

var fieldIDToName_AttachmentServiceGetPublicationReferenceStateResult = map[int16]string{
	0: "success",
}

type AttachmentServiceGetPublishedAttachmentContentArgs struct {
	Request *AttachmentIDRequest `thrift:"request,1" frugal:"1,default,AttachmentIDRequest" json:"request"`
}

func NewAttachmentServiceGetPublishedAttachmentContentArgs() *AttachmentServiceGetPublishedAttachmentContentArgs {
	return &AttachmentServiceGetPublishedAttachmentContentArgs{}
}

func (p *AttachmentServiceGetPublishedAttachmentContentArgs) InitDefault() {
}

var AttachmentServiceGetPublishedAttachmentContentArgs_Request_DEFAULT *AttachmentIDRequest

func (p *AttachmentServiceGetPublishedAttachmentContentArgs) GetRequest() (v *AttachmentIDRequest) {
	if !p.IsSetRequest() {
		return AttachmentServiceGetPublishedAttachmentContentArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *AttachmentServiceGetPublishedAttachmentContentArgs) SetRequest(val *AttachmentIDRequest) {
	p.Request = val
}

func (p *AttachmentServiceGetPublishedAttachmentContentArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AttachmentServiceGetPublishedAttachmentContentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceGetPublishedAttachmentContentArgs(%+v)", *p)
}

var fieldIDToName_AttachmentServiceGetPublishedAttachmentContentArgs = map[int16]string{
	1: "request",
}

type AttachmentServiceGetPublishedAttachmentContentResult struct {
	Success *AttachmentContent `thrift:"success,0,optional" frugal:"0,optional,AttachmentContent" json:"success,omitempty"`
}

func NewAttachmentServiceGetPublishedAttachmentContentResult() *AttachmentServiceGetPublishedAttachmentContentResult {
	return &AttachmentServiceGetPublishedAttachmentContentResult{}
}

func (p *AttachmentServiceGetPublishedAttachmentContentResult) InitDefault() {
}

var AttachmentServiceGetPublishedAttachmentContentResult_Success_DEFAULT *AttachmentContent

func (p *AttachmentServiceGetPublishedAttachmentContentResult) GetSuccess() (v *AttachmentContent) {
	if !p.IsSetSuccess() {
		return AttachmentServiceGetPublishedAttachmentContentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AttachmentServiceGetPublishedAttachmentContentResult) SetSuccess(x interface{}) {
	p.Success = x.(*AttachmentContent)
}

func (p *AttachmentServiceGetPublishedAttachmentContentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AttachmentServiceGetPublishedAttachmentContentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AttachmentServiceGetPublishedAttachmentContentResult(%+v)", *p)
}

var fieldIDToName_AttachmentServiceGetPublishedAttachmentContentResult = map[int16]string{
	0: "success",
}
