// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package identity

import (
	"context"
	"fmt"
	"github.com/HappyLadySauce/Knowledge-Core/kitex_gen/common"
)

const (
	CodeInvalidInput = 20001

	CodeConflict = 20002

	CodeInvalidCredentials = 20003

	CodeAccountLocked = 20004

	CodeUserDisabled = 20005

	CodeUserNotFound = 20006

	CodeUnauthenticated = 20007

	CodeForbidden = 20008

	CodeEmailNotVerified = 20010

	CodeInternal = 20999
)

type User struct {
	Id           int64  `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Username     string `thrift:"username,2,required" frugal:"2,required,string" json:"username"`
	Email        string `thrift:"email,3,required" frugal:"3,required,string" json:"email"`
	Role         string `thrift:"role,4,required" frugal:"4,required,string" json:"role"`
	Status       string `thrift:"status,5,required" frugal:"5,required,string" json:"status"`
	TokenVersion int64  `thrift:"token_version,6,required" frugal:"6,required,i64" json:"token_version"`
	Avatar       string `thrift:"avatar,7,required" frugal:"7,required,string" json:"avatar"`
	Bio          string `thrift:"bio,8,required" frugal:"8,required,string" json:"bio"`
	CreatedAt    string `thrift:"created_at,9,required" frugal:"9,required,string" json:"created_at"`
	UpdatedAt    string `thrift:"updated_at,10,required" frugal:"10,required,string" json:"updated_at"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetId() (v int64) {
	return p.Id
}

func (p *User) GetUsername() (v string) {
	return p.Username
}

func (p *User) GetEmail() (v string) {
	return p.Email
}

func (p *User) GetRole() (v string) {
	return p.Role
}

func (p *User) GetStatus() (v string) {
	return p.Status
}

func (p *User) GetTokenVersion() (v int64) {
	return p.TokenVersion
}

func (p *User) GetAvatar() (v string) {
	return p.Avatar
}

func (p *User) GetBio() (v string) {
	return p.Bio
}

func (p *User) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *User) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}
func (p *User) SetId(val int64) {
	p.Id = val
}
func (p *User) SetUsername(val string) {
	p.Username = val
}
func (p *User) SetEmail(val string) {
	p.Email = val
}
func (p *User) SetRole(val string) {
	p.Role = val
}
func (p *User) SetStatus(val string) {
	p.Status = val
}
func (p *User) SetTokenVersion(val int64) {
	p.TokenVersion = val
}
func (p *User) SetAvatar(val string) {
	p.Avatar = val
}
func (p *User) SetBio(val string) {
	p.Bio = val
}
func (p *User) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *User) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1:  "id",
	2:  "username",
	3:  "email",
	4:  "role",
	5:  "status",
	6:  "token_version",
	7:  "avatar",
	8:  "bio",
	9:  "created_at",
	10: "updated_at",
}

type PublicUser struct {
	Id       int64  `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Username string `thrift:"username,2,required" frugal:"2,required,string" json:"username"`
	Avatar   string `thrift:"avatar,3,required" frugal:"3,required,string" json:"avatar"`
}

func NewPublicUser() *PublicUser {
	return &PublicUser{}
}

func (p *PublicUser) InitDefault() {
}

func (p *PublicUser) GetId() (v int64) {
	return p.Id
}

func (p *PublicUser) GetUsername() (v string) {
	return p.Username
}

func (p *PublicUser) GetAvatar() (v string) {
	return p.Avatar
}
func (p *PublicUser) SetId(val int64) {
	p.Id = val
}
func (p *PublicUser) SetUsername(val string) {
	p.Username = val
}
func (p *PublicUser) SetAvatar(val string) {
	p.Avatar = val
}

func (p *PublicUser) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublicUser(%+v)", *p)
}

var fieldIDToName_PublicUser = map[int16]string{
	1: "id",
	2: "username",
	3: "avatar",
}

type RegisterRequest struct {
	Username string `thrift:"username,1,required" frugal:"1,required,string" json:"username"`
	Email    string `thrift:"email,2,required" frugal:"2,required,string" json:"email"`
	Password string `thrift:"password,3,required" frugal:"3,required,string" json:"password"`
}

func NewRegisterRequest() *RegisterRequest {
	return &RegisterRequest{}
}

func (p *RegisterRequest) InitDefault() {
}

func (p *RegisterRequest) GetUsername() (v string) {
	return p.Username
}

func (p *RegisterRequest) GetEmail() (v string) {
	return p.Email
}

func (p *RegisterRequest) GetPassword() (v string) {
	return p.Password
}
func (p *RegisterRequest) SetUsername(val string) {
	p.Username = val
}
func (p *RegisterRequest) SetEmail(val string) {
	p.Email = val
}
func (p *RegisterRequest) SetPassword(val string) {
	p.Password = val
}

func (p *RegisterRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterRequest(%+v)", *p)
}

var fieldIDToName_RegisterRequest = map[int16]string{
	1: "username",
	2: "email",
	3: "password",
}

type AuthenticateRequest struct {
	Identifier string `thrift:"identifier,1,required" frugal:"1,required,string" json:"identifier"`
	Password   string `thrift:"password,2,required" frugal:"2,required,string" json:"password"`
}

func NewAuthenticateRequest() *AuthenticateRequest {
	return &AuthenticateRequest{}
}

func (p *AuthenticateRequest) InitDefault() {
}

func (p *AuthenticateRequest) GetIdentifier() (v string) {
	return p.Identifier
}

func (p *AuthenticateRequest) GetPassword() (v string) {
	return p.Password
}
func (p *AuthenticateRequest) SetIdentifier(val string) {
	p.Identifier = val
}
func (p *AuthenticateRequest) SetPassword(val string) {
	p.Password = val
}

func (p *AuthenticateRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthenticateRequest(%+v)", *p)
}

var fieldIDToName_AuthenticateRequest = map[int16]string{
	1: "identifier",
	2: "password",
}

type Authentication struct {
	User         *User   `thrift:"user,1,required" frugal:"1,required,User" json:"user"`
	AccessToken  string  `thrift:"access_token,2,required" frugal:"2,required,string" json:"access_token"`
	ExpiresAt    string  `thrift:"expires_at,3,required" frugal:"3,required,string" json:"expires_at"`
	RefreshToken *string `thrift:"refresh_token,4,optional" frugal:"4,optional,string" json:"refresh_token,omitempty"`
	SessionId    *string `thrift:"session_id,5,optional" frugal:"5,optional,string" json:"session_id,omitempty"`
	TokenType    *string `thrift:"token_type,6,optional" frugal:"6,optional,string" json:"token_type,omitempty"`
}

func NewAuthentication() *Authentication {
	return &Authentication{}
}

func (p *Authentication) InitDefault() {
}

var Authentication_User_DEFAULT *User

func (p *Authentication) GetUser() (v *User) {
	if !p.IsSetUser() {
		return Authentication_User_DEFAULT
	}
	return p.User
}

func (p *Authentication) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *Authentication) GetExpiresAt() (v string) {
	return p.ExpiresAt
}

var Authentication_RefreshToken_DEFAULT string

func (p *Authentication) GetRefreshToken() (v string) {
	if !p.IsSetRefreshToken() {
		return Authentication_RefreshToken_DEFAULT
	}
	return *p.RefreshToken
}

var Authentication_SessionId_DEFAULT string

func (p *Authentication) GetSessionId() (v string) {
	if !p.IsSetSessionId() {
		return Authentication_SessionId_DEFAULT
	}
	return *p.SessionId
}

var Authentication_TokenType_DEFAULT string

func (p *Authentication) GetTokenType() (v string) {
	if !p.IsSetTokenType() {
		return Authentication_TokenType_DEFAULT
	}
	return *p.TokenType
}
func (p *Authentication) SetUser(val *User) {
	p.User = val
}
func (p *Authentication) SetAccessToken(val string) {
	p.AccessToken = val
}
func (p *Authentication) SetExpiresAt(val string) {
	p.ExpiresAt = val
}
func (p *Authentication) SetRefreshToken(val *string) {
	p.RefreshToken = val
}
func (p *Authentication) SetSessionId(val *string) {
	p.SessionId = val
}
func (p *Authentication) SetTokenType(val *string) {
	p.TokenType = val
}

func (p *Authentication) IsSetUser() bool {
	return p.User != nil
}

func (p *Authentication) IsSetRefreshToken() bool {
	return p.RefreshToken != nil
}

func (p *Authentication) IsSetSessionId() bool {
	return p.SessionId != nil
}

func (p *Authentication) IsSetTokenType() bool {
	return p.TokenType != nil
}

func (p *Authentication) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Authentication(%+v)", *p)
}

var fieldIDToName_Authentication = map[int16]string{
	1: "user",
	2: "access_token",
	3: "expires_at",
	4: "refresh_token",
	5: "session_id",
	6: "token_type",
}

type RefreshSessionRequest struct {
	RefreshToken string `thrift:"refresh_token,1,required" frugal:"1,required,string" json:"refresh_token"`
}

func NewRefreshSessionRequest() *RefreshSessionRequest {
	return &RefreshSessionRequest{}
}

func (p *RefreshSessionRequest) InitDefault() {
}

func (p *RefreshSessionRequest) GetRefreshToken() (v string) {
	return p.RefreshToken
}
func (p *RefreshSessionRequest) SetRefreshToken(val string) {
	p.RefreshToken = val
}

func (p *RefreshSessionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshSessionRequest(%+v)", *p)
}

var fieldIDToName_RefreshSessionRequest = map[int16]string{
	1: "refresh_token",
}

type EmailTokenRequest struct {
	Token string `thrift:"token,1,required" frugal:"1,required,string" json:"token"`
}

func NewEmailTokenRequest() *EmailTokenRequest {
	return &EmailTokenRequest{}
}

func (p *EmailTokenRequest) InitDefault() {
}

func (p *EmailTokenRequest) GetToken() (v string) {
	return p.Token
}
func (p *EmailTokenRequest) SetToken(val string) {
	p.Token = val
}

func (p *EmailTokenRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EmailTokenRequest(%+v)", *p)
}

var fieldIDToName_EmailTokenRequest = map[int16]string{
	1: "token",
}

type EmailRequest struct {
	Email string `thrift:"email,1,required" frugal:"1,required,string" json:"email"`
}

func NewEmailRequest() *EmailRequest {
	return &EmailRequest{}
}

func (p *EmailRequest) InitDefault() {
}

func (p *EmailRequest) GetEmail() (v string) {
	return p.Email
}
func (p *EmailRequest) SetEmail(val string) {
	p.Email = val
}

func (p *EmailRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EmailRequest(%+v)", *p)
}

var fieldIDToName_EmailRequest = map[int16]string{
	1: "email",
}

type PasswordResetRequest struct {
	Token    string `thrift:"token,1,required" frugal:"1,required,string" json:"token"`
	Password string `thrift:"password,2,required" frugal:"2,required,string" json:"password"`
}

func NewPasswordResetRequest() *PasswordResetRequest {
	return &PasswordResetRequest{}
}

func (p *PasswordResetRequest) InitDefault() {
}

func (p *PasswordResetRequest) GetToken() (v string) {
	return p.Token
}

func (p *PasswordResetRequest) GetPassword() (v string) {
	return p.Password
}
func (p *PasswordResetRequest) SetToken(val string) {
	p.Token = val
}
func (p *PasswordResetRequest) SetPassword(val string) {
	p.Password = val
}

func (p *PasswordResetRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PasswordResetRequest(%+v)", *p)
}

var fieldIDToName_PasswordResetRequest = map[int16]string{
	1: "token",
	2: "password",
}

type PasswordResetRequestRequest struct {
	Identifier string `thrift:"identifier,1,required" frugal:"1,required,string" json:"identifier"`
}

func NewPasswordResetRequestRequest() *PasswordResetRequestRequest {
	return &PasswordResetRequestRequest{}
}

func (p *PasswordResetRequestRequest) InitDefault() {
}

func (p *PasswordResetRequestRequest) GetIdentifier() (v string) {
	return p.Identifier
}
func (p *PasswordResetRequestRequest) SetIdentifier(val string) {
	p.Identifier = val
}

func (p *PasswordResetRequestRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PasswordResetRequestRequest(%+v)", *p)
}

var fieldIDToName_PasswordResetRequestRequest = map[int16]string{
	1: "identifier",
}

type SessionRequest struct {
	SessionId string `thrift:"session_id,1,required" frugal:"1,required,string" json:"session_id"`
}

func NewSessionRequest() *SessionRequest {
	return &SessionRequest{}
}

func (p *SessionRequest) InitDefault() {
}

func (p *SessionRequest) GetSessionId() (v string) {
	return p.SessionId
}
func (p *SessionRequest) SetSessionId(val string) {
	p.SessionId = val
}

func (p *SessionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SessionRequest(%+v)", *p)
}

var fieldIDToName_SessionRequest = map[int16]string{
	1: "session_id",
}

type DeactivateAccountRequest struct {
	Password string `thrift:"password,1,required" frugal:"1,required,string" json:"password"`
}

func NewDeactivateAccountRequest() *DeactivateAccountRequest {
	return &DeactivateAccountRequest{}
}

func (p *DeactivateAccountRequest) InitDefault() {
}

func (p *DeactivateAccountRequest) GetPassword() (v string) {
	return p.Password
}
func (p *DeactivateAccountRequest) SetPassword(val string) {
	p.Password = val
}

func (p *DeactivateAccountRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeactivateAccountRequest(%+v)", *p)
}

var fieldIDToName_DeactivateAccountRequest = map[int16]string{
	1: "password",
}

type Session struct {
	Id          string `thrift:"id,1,required" frugal:"1,required,string" json:"id"`
	DeviceLabel string `thrift:"device_label,2,required" frugal:"2,required,string" json:"device_label"`
	CreatedAt   string `thrift:"created_at,3,required" frugal:"3,required,string" json:"created_at"`
	LastSeenAt  string `thrift:"last_seen_at,4,required" frugal:"4,required,string" json:"last_seen_at"`
	ExpiresAt   string `thrift:"expires_at,5,required" frugal:"5,required,string" json:"expires_at"`
	Current     bool   `thrift:"current,6,required" frugal:"6,required,bool" json:"current"`
}

func NewSession() *Session {
	return &Session{}
}

func (p *Session) InitDefault() {
}

func (p *Session) GetId() (v string) {
	return p.Id
}

func (p *Session) GetDeviceLabel() (v string) {
	return p.DeviceLabel
}

func (p *Session) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *Session) GetLastSeenAt() (v string) {
	return p.LastSeenAt
}

func (p *Session) GetExpiresAt() (v string) {
	return p.ExpiresAt
}

func (p *Session) GetCurrent() (v bool) {
	return p.Current
}
func (p *Session) SetId(val string) {
	p.Id = val
}
func (p *Session) SetDeviceLabel(val string) {
	p.DeviceLabel = val
}
func (p *Session) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *Session) SetLastSeenAt(val string) {
	p.LastSeenAt = val
}
func (p *Session) SetExpiresAt(val string) {
	p.ExpiresAt = val
}
func (p *Session) SetCurrent(val bool) {
	p.Current = val
}

func (p *Session) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Session(%+v)", *p)
}

var fieldIDToName_Session = map[int16]string{
	1: "id",
	2: "device_label",
	3: "created_at",
	4: "last_seen_at",
	5: "expires_at",
	6: "current",
}

type SessionList struct {
	Items []*Session `thrift:"items,1,required" frugal:"1,required,list<Session>" json:"items"`
}

func NewSessionList() *SessionList {
	return &SessionList{}
}

func (p *SessionList) InitDefault() {
}

func (p *SessionList) GetItems() (v []*Session) {
	return p.Items
}
func (p *SessionList) SetItems(val []*Session) {
	p.Items = val
}

func (p *SessionList) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SessionList(%+v)", *p)
}

var fieldIDToName_SessionList = map[int16]string{
	1: "items",
}

type CurrentUserRequest struct {
}

func NewCurrentUserRequest() *CurrentUserRequest {
	return &CurrentUserRequest{}
}

func (p *CurrentUserRequest) InitDefault() {
}

func (p *CurrentUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CurrentUserRequest(%+v)", *p)
}

var fieldIDToName_CurrentUserRequest = map[int16]string{}

type ResolveUserRequest struct {
	Username string `thrift:"username,1,required" frugal:"1,required,string" json:"username"`
}

func NewResolveUserRequest() *ResolveUserRequest {
	return &ResolveUserRequest{}
}

func (p *ResolveUserRequest) InitDefault() {
}

func (p *ResolveUserRequest) GetUsername() (v string) {
	return p.Username
}
func (p *ResolveUserRequest) SetUsername(val string) {
	p.Username = val
}

func (p *ResolveUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResolveUserRequest(%+v)", *p)
}

var fieldIDToName_ResolveUserRequest = map[int16]string{
	1: "username",
}

type IdentityService interface {
	Ping(ctx context.Context, request *common.PingRequest) (r *common.PingResponse, err error)

	Register(ctx context.Context, request *RegisterRequest) (r *User, err error)

	Authenticate(ctx context.Context, request *AuthenticateRequest) (r *Authentication, err error)

	RefreshSession(ctx context.Context, request *RefreshSessionRequest) (r *Authentication, err error)

	RequestEmailVerification(ctx context.Context, request *EmailRequest) (r *common.EmptyResponse, err error)

	VerifyEmail(ctx context.Context, request *EmailTokenRequest) (r *common.EmptyResponse, err error)

	RequestPasswordReset(ctx context.Context, request *PasswordResetRequestRequest) (r *common.EmptyResponse, err error)

	ResetPassword(ctx context.Context, request *PasswordResetRequest) (r *common.EmptyResponse, err error)

	ListSessions(ctx context.Context, request *CurrentUserRequest) (r *SessionList, err error)

	RevokeSession(ctx context.Context, request *SessionRequest) (r *common.EmptyResponse, err error)

	RevokeAllSessions(ctx context.Context, request *CurrentUserRequest) (r *common.EmptyResponse, err error)

	DeactivateAccount(ctx context.Context, request *DeactivateAccountRequest) (r *common.EmptyResponse, err error)

	GetCurrentUser(ctx context.Context, request *CurrentUserRequest) (r *User, err error)

	ResolveUser(ctx context.Context, request *ResolveUserRequest) (r *PublicUser, err error)
}

type IdentityServicePingArgs struct {
	Request *common.PingRequest `thrift:"request,1" frugal:"1,default,common.PingRequest" json:"request"`
}

func NewIdentityServicePingArgs() *IdentityServicePingArgs {
	return &IdentityServicePingArgs{}
}

func (p *IdentityServicePingArgs) InitDefault() {
}

var IdentityServicePingArgs_Request_DEFAULT *common.PingRequest

func (p *IdentityServicePingArgs) GetRequest() (v *common.PingRequest) {
	if !p.IsSetRequest() {
		return IdentityServicePingArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *IdentityServicePingArgs) SetRequest(val *common.PingRequest) {
	p.Request = val
}

func (p *IdentityServicePingArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *IdentityServicePingArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServicePingArgs(%+v)", *p)
}

var fieldIDToName_IdentityServicePingArgs = map[int16]string{
	1: "request",
}

type IdentityServicePingResult struct {
	Success *common.PingResponse `thrift:"success,0,optional" frugal:"0,optional,common.PingResponse" json:"success,omitempty"`
}

func NewIdentityServicePingResult() *IdentityServicePingResult {
	return &IdentityServicePingResult{}
}

func (p *IdentityServicePingResult) InitDefault() {
}

var IdentityServicePingResult_Success_DEFAULT *common.PingResponse

func (p *IdentityServicePingResult) GetSuccess() (v *common.PingResponse) {
	if !p.IsSetSuccess() {
		return IdentityServicePingResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IdentityServicePingResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.PingResponse)
}

func (p *IdentityServicePingResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IdentityServicePingResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServicePingResult(%+v)", *p)
}

var fieldIDToName_IdentityServicePingResult = map[int16]string{
	0: "success",
}

type IdentityServiceRegisterArgs struct {
	Request *RegisterRequest `thrift:"request,1" frugal:"1,default,RegisterRequest" json:"request"`
}

func NewIdentityServiceRegisterArgs() *IdentityServiceRegisterArgs {
	return &IdentityServiceRegisterArgs{}
}

func (p *IdentityServiceRegisterArgs) InitDefault() {
}

var IdentityServiceRegisterArgs_Request_DEFAULT *RegisterRequest

func (p *IdentityServiceRegisterArgs) GetRequest() (v *RegisterRequest) {
	if !p.IsSetRequest() {
		return IdentityServiceRegisterArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *IdentityServiceRegisterArgs) SetRequest(val *RegisterRequest) {
	p.Request = val
}

func (p *IdentityServiceRegisterArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *IdentityServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_IdentityServiceRegisterArgs = map[int16]string{
	1: "request",
}

type IdentityServiceRegisterResult struct {
	Success *User `thrift:"success,0,optional" frugal:"0,optional,User" json:"success,omitempty"`
}

func NewIdentityServiceRegisterResult() *IdentityServiceRegisterResult {
	return &IdentityServiceRegisterResult{}
}

func (p *IdentityServiceRegisterResult) InitDefault() {
}

var IdentityServiceRegisterResult_Success_DEFAULT *User

func (p *IdentityServiceRegisterResult) GetSuccess() (v *User) {
	if !p.IsSetSuccess() {
		return IdentityServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IdentityServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*User)
}

func (p *IdentityServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IdentityServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_IdentityServiceRegisterResult = map[int16]string{
	0: "success",
}

type IdentityServiceAuthenticateArgs struct {
	Request *AuthenticateRequest `thrift:"request,1" frugal:"1,default,AuthenticateRequest" json:"request"`
}

func NewIdentityServiceAuthenticateArgs() *IdentityServiceAuthenticateArgs {
	return &IdentityServiceAuthenticateArgs{}
}

func (p *IdentityServiceAuthenticateArgs) InitDefault() {
}

var IdentityServiceAuthenticateArgs_Request_DEFAULT *AuthenticateRequest

func (p *IdentityServiceAuthenticateArgs) GetRequest() (v *AuthenticateRequest) {
	if !p.IsSetRequest() {
		return IdentityServiceAuthenticateArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *IdentityServiceAuthenticateArgs) SetRequest(val *AuthenticateRequest) {
	p.Request = val
}

func (p *IdentityServiceAuthenticateArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *IdentityServiceAuthenticateArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceAuthenticateArgs(%+v)", *p)
}

var fieldIDToName_IdentityServiceAuthenticateArgs = map[int16]string{
	1: "request",
}

type IdentityServiceAuthenticateResult struct {
	Success *Authentication `thrift:"success,0,optional" frugal:"0,optional,Authentication" json:"success,omitempty"`
}

func NewIdentityServiceAuthenticateResult() *IdentityServiceAuthenticateResult {
	return &IdentityServiceAuthenticateResult{}
}

func (p *IdentityServiceAuthenticateResult) InitDefault() {
}

var IdentityServiceAuthenticateResult_Success_DEFAULT *Authentication

func (p *IdentityServiceAuthenticateResult) GetSuccess() (v *Authentication) {
	if !p.IsSetSuccess() {
		return IdentityServiceAuthenticateResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IdentityServiceAuthenticateResult) SetSuccess(x interface{}) {
	p.Success = x.(*Authentication)
}

func (p *IdentityServiceAuthenticateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IdentityServiceAuthenticateResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceAuthenticateResult(%+v)", *p)
}

var fieldIDToName_IdentityServiceAuthenticateResult = map[int16]string{
	0: "success",
}

type IdentityServiceRefreshSessionArgs struct {
	Request *RefreshSessionRequest `thrift:"request,1" frugal:"1,default,RefreshSessionRequest" json:"request"`
}

func NewIdentityServiceRefreshSessionArgs() *IdentityServiceRefreshSessionArgs {
	return &IdentityServiceRefreshSessionArgs{}
}

func (p *IdentityServiceRefreshSessionArgs) InitDefault() {
}

var IdentityServiceRefreshSessionArgs_Request_DEFAULT *RefreshSessionRequest

func (p *IdentityServiceRefreshSessionArgs) GetRequest() (v *RefreshSessionRequest) {
	if !p.IsSetRequest() {
		return IdentityServiceRefreshSessionArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *IdentityServiceRefreshSessionArgs) SetRequest(val *RefreshSessionRequest) {
	p.Request = val
}

func (p *IdentityServiceRefreshSessionArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *IdentityServiceRefreshSessionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceRefreshSessionArgs(%+v)", *p)
}

var fieldIDToName_IdentityServiceRefreshSessionArgs = map[int16]string{
	1: "request",
}

type IdentityServiceRefreshSessionResult struct {
	Success *Authentication `thrift:"success,0,optional" frugal:"0,optional,Authentication" json:"success,omitempty"`
}

func NewIdentityServiceRefreshSessionResult() *IdentityServiceRefreshSessionResult {
	return &IdentityServiceRefreshSessionResult{}
}

func (p *IdentityServiceRefreshSessionResult) InitDefault() {
}

var IdentityServiceRefreshSessionResult_Success_DEFAULT *Authentication

func (p *IdentityServiceRefreshSessionResult) GetSuccess() (v *Authentication) {
	if !p.IsSetSuccess() {
		return IdentityServiceRefreshSessionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IdentityServiceRefreshSessionResult) SetSuccess(x interface{}) {
	p.Success = x.(*Authentication)
}

func (p *IdentityServiceRefreshSessionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IdentityServiceRefreshSessionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceRefreshSessionResult(%+v)", *p)
}

var fieldIDToName_IdentityServiceRefreshSessionResult = map[int16]string{
	0: "success",
}

type IdentityServiceRequestEmailVerificationArgs struct {
	Request *EmailRequest `thrift:"request,1" frugal:"1,default,EmailRequest" json:"request"`
}

func NewIdentityServiceRequestEmailVerificationArgs() *IdentityServiceRequestEmailVerificationArgs {
	return &IdentityServiceRequestEmailVerificationArgs{}
}

func (p *IdentityServiceRequestEmailVerificationArgs) InitDefault() {
}

var IdentityServiceRequestEmailVerificationArgs_Request_DEFAULT *EmailRequest

func (p *IdentityServiceRequestEmailVerificationArgs) GetRequest() (v *EmailRequest) {
	if !p.IsSetRequest() {
		return IdentityServiceRequestEmailVerificationArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *IdentityServiceRequestEmailVerificationArgs) SetRequest(val *EmailRequest) {
	p.Request = val
}

func (p *IdentityServiceRequestEmailVerificationArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *IdentityServiceRequestEmailVerificationArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceRequestEmailVerificationArgs(%+v)", *p)
}

var fieldIDToName_IdentityServiceRequestEmailVerificationArgs = map[int16]string{
	1: "request",
}

type IdentityServiceRequestEmailVerificationResult struct {
	Success *common.EmptyResponse `thrift:"success,0,optional" frugal:"0,optional,common.EmptyResponse" json:"success,omitempty"`
}

func NewIdentityServiceRequestEmailVerificationResult() *IdentityServiceRequestEmailVerificationResult {
	return &IdentityServiceRequestEmailVerificationResult{}
}

func (p *IdentityServiceRequestEmailVerificationResult) InitDefault() {
}

var IdentityServiceRequestEmailVerificationResult_Success_DEFAULT *common.EmptyResponse

func (p *IdentityServiceRequestEmailVerificationResult) GetSuccess() (v *common.EmptyResponse) {
	if !p.IsSetSuccess() {
		return IdentityServiceRequestEmailVerificationResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IdentityServiceRequestEmailVerificationResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.EmptyResponse)
}

func (p *IdentityServiceRequestEmailVerificationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IdentityServiceRequestEmailVerificationResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceRequestEmailVerificationResult(%+v)", *p)
}

var fieldIDToName_IdentityServiceRequestEmailVerificationResult = map[int16]string{
	0: "success",
}

type IdentityServiceVerifyEmailArgs struct {
	Request *EmailTokenRequest `thrift:"request,1" frugal:"1,default,EmailTokenRequest" json:"request"`
}

func NewIdentityServiceVerifyEmailArgs() *IdentityServiceVerifyEmailArgs {
	return &IdentityServiceVerifyEmailArgs{}
}

func (p *IdentityServiceVerifyEmailArgs) InitDefault() {
}

var IdentityServiceVerifyEmailArgs_Request_DEFAULT *EmailTokenRequest

func (p *IdentityServiceVerifyEmailArgs) GetRequest() (v *EmailTokenRequest) {
	if !p.IsSetRequest() {
		return IdentityServiceVerifyEmailArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *IdentityServiceVerifyEmailArgs) SetRequest(val *EmailTokenRequest) {
	p.Request = val
}

func (p *IdentityServiceVerifyEmailArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *IdentityServiceVerifyEmailArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceVerifyEmailArgs(%+v)", *p)
}

var fieldIDToName_IdentityServiceVerifyEmailArgs = map[int16]string{
	1: "request",
}

type IdentityServiceVerifyEmailResult struct {
	Success *common.EmptyResponse `thrift:"success,0,optional" frugal:"0,optional,common.EmptyResponse" json:"success,omitempty"`
}

func NewIdentityServiceVerifyEmailResult() *IdentityServiceVerifyEmailResult {
	return &IdentityServiceVerifyEmailResult{}
}

func (p *IdentityServiceVerifyEmailResult) InitDefault() {
}

var IdentityServiceVerifyEmailResult_Success_DEFAULT *common.EmptyResponse

func (p *IdentityServiceVerifyEmailResult) GetSuccess() (v *common.EmptyResponse) {
	if !p.IsSetSuccess() {
		return IdentityServiceVerifyEmailResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IdentityServiceVerifyEmailResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.EmptyResponse)
}

func (p *IdentityServiceVerifyEmailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IdentityServiceVerifyEmailResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceVerifyEmailResult(%+v)", *p)
}

var fieldIDToName_IdentityServiceVerifyEmailResult = map[int16]string{
	0: "success",
}

type IdentityServiceRequestPasswordResetArgs struct {
	Request *PasswordResetRequestRequest `thrift:"request,1" frugal:"1,default,PasswordResetRequestRequest" json:"request"`
}

func NewIdentityServiceRequestPasswordResetArgs() *IdentityServiceRequestPasswordResetArgs {
	return &IdentityServiceRequestPasswordResetArgs{}
}

func (p *IdentityServiceRequestPasswordResetArgs) InitDefault() {
}

var IdentityServiceRequestPasswordResetArgs_Request_DEFAULT *PasswordResetRequestRequest

func (p *IdentityServiceRequestPasswordResetArgs) GetRequest() (v *PasswordResetRequestRequest) {
	if !p.IsSetRequest() {
		return IdentityServiceRequestPasswordResetArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *IdentityServiceRequestPasswordResetArgs) SetRequest(val *PasswordResetRequestRequest) {
	p.Request = val
}

func (p *IdentityServiceRequestPasswordResetArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *IdentityServiceRequestPasswordResetArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceRequestPasswordResetArgs(%+v)", *p)
}

var fieldIDToName_IdentityServiceRequestPasswordResetArgs = map[int16]string{
	1: "request",
}

type IdentityServiceRequestPasswordResetResult struct {
	Success *common.EmptyResponse `thrift:"success,0,optional" frugal:"0,optional,common.EmptyResponse" json:"success,omitempty"`
}

func NewIdentityServiceRequestPasswordResetResult() *IdentityServiceRequestPasswordResetResult {
	return &IdentityServiceRequestPasswordResetResult{}
}

func (p *IdentityServiceRequestPasswordResetResult) InitDefault() {
}

var IdentityServiceRequestPasswordResetResult_Success_DEFAULT *common.EmptyResponse

func (p *IdentityServiceRequestPasswordResetResult) GetSuccess() (v *common.EmptyResponse) {
	if !p.IsSetSuccess() {
		return IdentityServiceRequestPasswordResetResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IdentityServiceRequestPasswordResetResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.EmptyResponse)
}

func (p *IdentityServiceRequestPasswordResetResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IdentityServiceRequestPasswordResetResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceRequestPasswordResetResult(%+v)", *p)
}

var fieldIDToName_IdentityServiceRequestPasswordResetResult = map[int16]string{
	0: "success",
}

type IdentityServiceResetPasswordArgs struct {
	Request *PasswordResetRequest `thrift:"request,1" frugal:"1,default,PasswordResetRequest" json:"request"`
}

func NewIdentityServiceResetPasswordArgs() *IdentityServiceResetPasswordArgs {
	return &IdentityServiceResetPasswordArgs{}
}

func (p *IdentityServiceResetPasswordArgs) InitDefault() {
}

var IdentityServiceResetPasswordArgs_Request_DEFAULT *PasswordResetRequest

func (p *IdentityServiceResetPasswordArgs) GetRequest() (v *PasswordResetRequest) {
	if !p.IsSetRequest() {
		return IdentityServiceResetPasswordArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *IdentityServiceResetPasswordArgs) SetRequest(val *PasswordResetRequest) {
	p.Request = val
}

func (p *IdentityServiceResetPasswordArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *IdentityServiceResetPasswordArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceResetPasswordArgs(%+v)", *p)
}

var fieldIDToName_IdentityServiceResetPasswordArgs = map[int16]string{
	1: "request",
}

type IdentityServiceResetPasswordResult struct {
	Success *common.EmptyResponse `thrift:"success,0,optional" frugal:"0,optional,common.EmptyResponse" json:"success,omitempty"`
}

func NewIdentityServiceResetPasswordResult() *IdentityServiceResetPasswordResult {
	return &IdentityServiceResetPasswordResult{}
}

func (p *IdentityServiceResetPasswordResult) InitDefault() {
}

var IdentityServiceResetPasswordResult_Success_DEFAULT *common.EmptyResponse

func (p *IdentityServiceResetPasswordResult) GetSuccess() (v *common.EmptyResponse) {
	if !p.IsSetSuccess() {
		return IdentityServiceResetPasswordResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IdentityServiceResetPasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.EmptyResponse)
}

func (p *IdentityServiceResetPasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IdentityServiceResetPasswordResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceResetPasswordResult(%+v)", *p)
}

var fieldIDToName_IdentityServiceResetPasswordResult = map[int16]string{
	0: "success",
}

type IdentityServiceListSessionsArgs struct {
	Request *CurrentUserRequest `thrift:"request,1" frugal:"1,default,CurrentUserRequest" json:"request"`
}

func NewIdentityServiceListSessionsArgs() *IdentityServiceListSessionsArgs {
	return &IdentityServiceListSessionsArgs{}
}

func (p *IdentityServiceListSessionsArgs) InitDefault() {
}

var IdentityServiceListSessionsArgs_Request_DEFAULT *CurrentUserRequest

func (p *IdentityServiceListSessionsArgs) GetRequest() (v *CurrentUserRequest) {
	if !p.IsSetRequest() {
		return IdentityServiceListSessionsArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *IdentityServiceListSessionsArgs) SetRequest(val *CurrentUserRequest) {
	p.Request = val
}

func (p *IdentityServiceListSessionsArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *IdentityServiceListSessionsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceListSessionsArgs(%+v)", *p)
}

var fieldIDToName_IdentityServiceListSessionsArgs = map[int16]string{
	1: "request",
}

type IdentityServiceListSessionsResult struct {
	Success *SessionList `thrift:"success,0,optional" frugal:"0,optional,SessionList" json:"success,omitempty"`
}

func NewIdentityServiceListSessionsResult() *IdentityServiceListSessionsResult {
	return &IdentityServiceListSessionsResult{}
}

func (p *IdentityServiceListSessionsResult) InitDefault() {
}

var IdentityServiceListSessionsResult_Success_DEFAULT *SessionList

func (p *IdentityServiceListSessionsResult) GetSuccess() (v *SessionList) {
	if !p.IsSetSuccess() {
		return IdentityServiceListSessionsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IdentityServiceListSessionsResult) SetSuccess(x interface{}) {
	p.Success = x.(*SessionList)
}

func (p *IdentityServiceListSessionsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IdentityServiceListSessionsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceListSessionsResult(%+v)", *p)
}

var fieldIDToName_IdentityServiceListSessionsResult = map[int16]string{
	0: "success",
}

type IdentityServiceRevokeSessionArgs struct {
	Request *SessionRequest `thrift:"request,1" frugal:"1,default,SessionRequest" json:"request"`
}

func NewIdentityServiceRevokeSessionArgs() *IdentityServiceRevokeSessionArgs {
	return &IdentityServiceRevokeSessionArgs{}
}

func (p *IdentityServiceRevokeSessionArgs) InitDefault() {
}

var IdentityServiceRevokeSessionArgs_Request_DEFAULT *SessionRequest

func (p *IdentityServiceRevokeSessionArgs) GetRequest() (v *SessionRequest) {
	if !p.IsSetRequest() {
		return IdentityServiceRevokeSessionArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *IdentityServiceRevokeSessionArgs) SetRequest(val *SessionRequest) {
	p.Request = val
}

func (p *IdentityServiceRevokeSessionArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *IdentityServiceRevokeSessionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceRevokeSessionArgs(%+v)", *p)
}

var fieldIDToName_IdentityServiceRevokeSessionArgs = map[int16]string{
	1: "request",
}

type IdentityServiceRevokeSessionResult struct {
	Success *common.EmptyResponse `thrift:"success,0,optional" frugal:"0,optional,common.EmptyResponse" json:"success,omitempty"`
}

func NewIdentityServiceRevokeSessionResult() *IdentityServiceRevokeSessionResult {
	return &IdentityServiceRevokeSessionResult{}
}

func (p *IdentityServiceRevokeSessionResult) InitDefault() {
}

var IdentityServiceRevokeSessionResult_Success_DEFAULT *common.EmptyResponse

func (p *IdentityServiceRevokeSessionResult) GetSuccess() (v *common.EmptyResponse) {
	if !p.IsSetSuccess() {
		return IdentityServiceRevokeSessionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IdentityServiceRevokeSessionResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.EmptyResponse)
}

func (p *IdentityServiceRevokeSessionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IdentityServiceRevokeSessionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceRevokeSessionResult(%+v)", *p)
}

var fieldIDToName_IdentityServiceRevokeSessionResult = map[int16]string{
	0: "success",
}

type IdentityServiceRevokeAllSessionsArgs struct {
	Request *CurrentUserRequest `thrift:"request,1" frugal:"1,default,CurrentUserRequest" json:"request"`
}

func NewIdentityServiceRevokeAllSessionsArgs() *IdentityServiceRevokeAllSessionsArgs {
	return &IdentityServiceRevokeAllSessionsArgs{}
}

func (p *IdentityServiceRevokeAllSessionsArgs) InitDefault() {
}

var IdentityServiceRevokeAllSessionsArgs_Request_DEFAULT *CurrentUserRequest

func (p *IdentityServiceRevokeAllSessionsArgs) GetRequest() (v *CurrentUserRequest) {
	if !p.IsSetRequest() {
		return IdentityServiceRevokeAllSessionsArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *IdentityServiceRevokeAllSessionsArgs) SetRequest(val *CurrentUserRequest) {
	p.Request = val
}

func (p *IdentityServiceRevokeAllSessionsArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *IdentityServiceRevokeAllSessionsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceRevokeAllSessionsArgs(%+v)", *p)
}

var fieldIDToName_IdentityServiceRevokeAllSessionsArgs = map[int16]string{
	1: "request",
}

type IdentityServiceRevokeAllSessionsResult struct {
	Success *common.EmptyResponse `thrift:"success,0,optional" frugal:"0,optional,common.EmptyResponse" json:"success,omitempty"`
}

func NewIdentityServiceRevokeAllSessionsResult() *IdentityServiceRevokeAllSessionsResult {
	return &IdentityServiceRevokeAllSessionsResult{}
}

func (p *IdentityServiceRevokeAllSessionsResult) InitDefault() {
}

var IdentityServiceRevokeAllSessionsResult_Success_DEFAULT *common.EmptyResponse

func (p *IdentityServiceRevokeAllSessionsResult) GetSuccess() (v *common.EmptyResponse) {
	if !p.IsSetSuccess() {
		return IdentityServiceRevokeAllSessionsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IdentityServiceRevokeAllSessionsResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.EmptyResponse)
}

func (p *IdentityServiceRevokeAllSessionsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IdentityServiceRevokeAllSessionsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceRevokeAllSessionsResult(%+v)", *p)
}

var fieldIDToName_IdentityServiceRevokeAllSessionsResult = map[int16]string{
	0: "success",
}

type IdentityServiceDeactivateAccountArgs struct {
	Request *DeactivateAccountRequest `thrift:"request,1" frugal:"1,default,DeactivateAccountRequest" json:"request"`
}

func NewIdentityServiceDeactivateAccountArgs() *IdentityServiceDeactivateAccountArgs {
	return &IdentityServiceDeactivateAccountArgs{}
}

func (p *IdentityServiceDeactivateAccountArgs) InitDefault() {
}

var IdentityServiceDeactivateAccountArgs_Request_DEFAULT *DeactivateAccountRequest

func (p *IdentityServiceDeactivateAccountArgs) GetRequest() (v *DeactivateAccountRequest) {
	if !p.IsSetRequest() {
		return IdentityServiceDeactivateAccountArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *IdentityServiceDeactivateAccountArgs) SetRequest(val *DeactivateAccountRequest) {
	p.Request = val
}

func (p *IdentityServiceDeactivateAccountArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *IdentityServiceDeactivateAccountArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceDeactivateAccountArgs(%+v)", *p)
}

var fieldIDToName_IdentityServiceDeactivateAccountArgs = map[int16]string{
	1: "request",
}

type IdentityServiceDeactivateAccountResult struct {
	Success *common.EmptyResponse `thrift:"success,0,optional" frugal:"0,optional,common.EmptyResponse" json:"success,omitempty"`
}

func NewIdentityServiceDeactivateAccountResult() *IdentityServiceDeactivateAccountResult {
	return &IdentityServiceDeactivateAccountResult{}
}

func (p *IdentityServiceDeactivateAccountResult) InitDefault() {
}

var IdentityServiceDeactivateAccountResult_Success_DEFAULT *common.EmptyResponse

func (p *IdentityServiceDeactivateAccountResult) GetSuccess() (v *common.EmptyResponse) {
	if !p.IsSetSuccess() {
		return IdentityServiceDeactivateAccountResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IdentityServiceDeactivateAccountResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.EmptyResponse)
}

func (p *IdentityServiceDeactivateAccountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IdentityServiceDeactivateAccountResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceDeactivateAccountResult(%+v)", *p)
}

var fieldIDToName_IdentityServiceDeactivateAccountResult = map[int16]string{
	0: "success",
}

type IdentityServiceGetCurrentUserArgs struct {
	Request *CurrentUserRequest `thrift:"request,1" frugal:"1,default,CurrentUserRequest" json:"request"`
}

func NewIdentityServiceGetCurrentUserArgs() *IdentityServiceGetCurrentUserArgs {
	return &IdentityServiceGetCurrentUserArgs{}
}

func (p *IdentityServiceGetCurrentUserArgs) InitDefault() {
}

var IdentityServiceGetCurrentUserArgs_Request_DEFAULT *CurrentUserRequest

func (p *IdentityServiceGetCurrentUserArgs) GetRequest() (v *CurrentUserRequest) {
	if !p.IsSetRequest() {
		return IdentityServiceGetCurrentUserArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *IdentityServiceGetCurrentUserArgs) SetRequest(val *CurrentUserRequest) {
	p.Request = val
}

func (p *IdentityServiceGetCurrentUserArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *IdentityServiceGetCurrentUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceGetCurrentUserArgs(%+v)", *p)
}

var fieldIDToName_IdentityServiceGetCurrentUserArgs = map[int16]string{
	1: "request",
}

type IdentityServiceGetCurrentUserResult struct {
	Success *User `thrift:"success,0,optional" frugal:"0,optional,User" json:"success,omitempty"`
}

func NewIdentityServiceGetCurrentUserResult() *IdentityServiceGetCurrentUserResult {
	return &IdentityServiceGetCurrentUserResult{}
}

func (p *IdentityServiceGetCurrentUserResult) InitDefault() {
}

var IdentityServiceGetCurrentUserResult_Success_DEFAULT *User

func (p *IdentityServiceGetCurrentUserResult) GetSuccess() (v *User) {
	if !p.IsSetSuccess() {
		return IdentityServiceGetCurrentUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IdentityServiceGetCurrentUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*User)
}

func (p *IdentityServiceGetCurrentUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IdentityServiceGetCurrentUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceGetCurrentUserResult(%+v)", *p)
}

var fieldIDToName_IdentityServiceGetCurrentUserResult = map[int16]string{
	0: "success",
}

type IdentityServiceResolveUserArgs struct {
	Request *ResolveUserRequest `thrift:"request,1" frugal:"1,default,ResolveUserRequest" json:"request"`
}

func NewIdentityServiceResolveUserArgs() *IdentityServiceResolveUserArgs {
	return &IdentityServiceResolveUserArgs{}
}

func (p *IdentityServiceResolveUserArgs) InitDefault() {
}

var IdentityServiceResolveUserArgs_Request_DEFAULT *ResolveUserRequest

func (p *IdentityServiceResolveUserArgs) GetRequest() (v *ResolveUserRequest) {
	if !p.IsSetRequest() {
		return IdentityServiceResolveUserArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *IdentityServiceResolveUserArgs) SetRequest(val *ResolveUserRequest) {
	p.Request = val
}

func (p *IdentityServiceResolveUserArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *IdentityServiceResolveUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceResolveUserArgs(%+v)", *p)
}

var fieldIDToName_IdentityServiceResolveUserArgs = map[int16]string{
	1: "request",
}

type IdentityServiceResolveUserResult struct {
	Success *PublicUser `thrift:"success,0,optional" frugal:"0,optional,PublicUser" json:"success,omitempty"`
}

func NewIdentityServiceResolveUserResult() *IdentityServiceResolveUserResult {
	return &IdentityServiceResolveUserResult{}
}

func (p *IdentityServiceResolveUserResult) InitDefault() {
}

var IdentityServiceResolveUserResult_Success_DEFAULT *PublicUser

func (p *IdentityServiceResolveUserResult) GetSuccess() (v *PublicUser) {
	if !p.IsSetSuccess() {
		return IdentityServiceResolveUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IdentityServiceResolveUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*PublicUser)
}

func (p *IdentityServiceResolveUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IdentityServiceResolveUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServiceResolveUserResult(%+v)", *p)
}

var fieldIDToName_IdentityServiceResolveUserResult = map[int16]string{
	0: "success",
}
