// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package identity

import (
	"context"
	"fmt"
	"github.com/HappyLadySauce/Knowledge-Core/kitex_gen/common"
)

type IdentityService interface {
	Ping(ctx context.Context, request *common.PingRequest) (r *common.PingResponse, err error)
}

type IdentityServicePingArgs struct {
	Request *common.PingRequest `thrift:"request,1" frugal:"1,default,common.PingRequest" json:"request"`
}

func NewIdentityServicePingArgs() *IdentityServicePingArgs {
	return &IdentityServicePingArgs{}
}

func (p *IdentityServicePingArgs) InitDefault() {
}

var IdentityServicePingArgs_Request_DEFAULT *common.PingRequest

func (p *IdentityServicePingArgs) GetRequest() (v *common.PingRequest) {
	if !p.IsSetRequest() {
		return IdentityServicePingArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *IdentityServicePingArgs) SetRequest(val *common.PingRequest) {
	p.Request = val
}

func (p *IdentityServicePingArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *IdentityServicePingArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServicePingArgs(%+v)", *p)
}

var fieldIDToName_IdentityServicePingArgs = map[int16]string{
	1: "request",
}

type IdentityServicePingResult struct {
	Success *common.PingResponse `thrift:"success,0,optional" frugal:"0,optional,common.PingResponse" json:"success,omitempty"`
}

func NewIdentityServicePingResult() *IdentityServicePingResult {
	return &IdentityServicePingResult{}
}

func (p *IdentityServicePingResult) InitDefault() {
}

var IdentityServicePingResult_Success_DEFAULT *common.PingResponse

func (p *IdentityServicePingResult) GetSuccess() (v *common.PingResponse) {
	if !p.IsSetSuccess() {
		return IdentityServicePingResult_Success_DEFAULT
	}
	return p.Success
}
func (p *IdentityServicePingResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.PingResponse)
}

func (p *IdentityServicePingResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IdentityServicePingResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IdentityServicePingResult(%+v)", *p)
}

var fieldIDToName_IdentityServicePingResult = map[int16]string{
	0: "success",
}
