apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: argo-events
spec:
  template:
    spec:
      containers:
        - name: controller-manager
          env:
            - name: ARGO_EVENTS_IMAGE
              value: quay.io/argoproj/argo-events@sha256:fa07b2c9ece6ec60a3a8377866dfe21e8bad062d5b5407f1f181d3f1d24fb861
