apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ci

resources:
  - namespace.yaml
  - upstream/argo-workflows-v4.0.8.yaml
  - upstream/argo-events-v1.9.11.yaml

images:
  - name: quay.io/argoproj/workflow-controller
    newName: quay.io/argoproj/workflow-controller
    digest: sha256:7a156419f80285859fc8f859927b6cc249f0d128e161e080dc17fca8fcbbceb6
  - name: quay.io/argoproj/argocli
    newName: quay.io/argoproj/argocli
    digest: sha256:83e93aa9149a51da998c1df4abea7ae2c504e0b0a5892052dc092740f68323e8
  - name: quay.io/argoproj/argo-events
    newName: quay.io/argoproj/argo-events
    digest: sha256:fa07b2c9ece6ec60a3a8377866dfe21e8bad062d5b5407f1f181d3f1d24fb861

patches:
  - path: workflow-controller-config.yaml
  - path: controller-security.yaml
  - path: events-controller-image.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: knowledge-core-ci
    includeTemplates: true
