apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  executor: |
    image: quay.io/argoproj/argoexec@sha256:86a965d7eea176959351156e24f3a2fa8d8e342e477ef425009af95a12e3fe87
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 200m
        memory: 256Mi
